digital-asset/daml-finance

- src/main/daml/Daml/Finance/RefData/Time/DateClock.daml
- src/test/daml/Daml/Finance/Bond/Test/Util.daml
- src/test/daml/Daml/Finance/Derivative/Test/CallableBond.daml
- src/test/daml/Daml/Finance/Derivative/Test/EuropeanOption.daml
- src/test/daml/Daml/Finance/Derivative/Test/ForwardCash.daml
- src/test/daml/Daml/Finance/Derivative/Test/ForwardPhysical.daml
- src/test/daml/Daml/Finance/Derivative/Test/Intermediated/BondCoupon.daml
- src/test/daml/Daml/Finance/Equity/Test/CashDividend.daml
- src/test/daml/Daml/Finance/Equity/Test/CashTakeover.daml
- src/test/daml/Daml/Finance/Equity/Test/Merger.daml
- src/test/daml/Daml/Finance/Equity/Test/ShareDividend.daml
- src/test/daml/Daml/Finance/Equity/Test/ShareTakeover.daml
Addresses https://github.com/DACH-NY/daml-finance/issues/263
> `DateClock` implements `Disclosure`

- docs/Tutorials/1_Getting_Started/example/daml/Scripts/Setup.daml
- docs/Tutorials/1_Getting_Started/example/daml/Workflow/CreateAccount.daml
- docs/Tutorials/1_Getting_Started/example/daml/Workflow/Deposit.daml
- docs/Tutorials/1_Getting_Started/example/daml/Workflow/Transfer.daml
Temporarily updating the getting started code in the repo, so that new users can consume it.
Currently I am facing issues building the getting started code in the `daml` repo using the local SDK, probably because of in-flight interface changes.
> Update getting started tutorial code

- src/main/daml/Daml/Finance/Bond/FixedRate.daml
- src/main/daml/Daml/Finance/Bond/FloatingRate.daml
- src/main/daml/Daml/Finance/Bond/InflationLinked.daml
- src/main/daml/Daml/Finance/Bond/ZeroCoupon.daml
- src/main/daml/Daml/Finance/Interface/Derivative/HasClaims.daml
- src/test/daml/Daml/Finance/Bond/Test/Util.daml
- Named some fields more explicitly
- Improved some comments
> Small bond improvements

- docs/README.md
- docs/source/getting-started/getting-started.rst
- docs/source/getting-started/install-daml-finance.rst
- docs/source/getting-started/intro.rst
- docs/source/getting-started/lifecycling.rst
- docs/source/getting-started/settlement.rst
- docs/source/getting-started/transfer.rst
- docs/source/index.rst
- docs/source/tutorial/bond-extension.rst
- docs/source/tutorial/contingent-claims-instrument.rst
- docs/source/tutorial/contingent-claims-on-ledger-vs-on-the-fly.rst
- docs/source/tutorial/contingent-claims-on-vs-off-ledger.rst
- docs/source/tutorial/derivative-extension.rst
- docs/source/tutorial/intro.rst
- src/main/daml/Daml/Finance/Bond/FixedRate.daml
- src/main/daml/Daml/Finance/Bond/FloatingRate.daml
- src/main/daml/Daml/Finance/Bond/Util.daml
- src/test/daml/Daml/Finance/Bond/Test/FixedRate.daml
- src/test/daml/Daml/Finance/Bond/Test/FloatingRate.daml
- src/test/daml/Daml/Finance/Bond/Test/InflationLinked.daml
- src/test/daml/Daml/Finance/Bond/Test/Util.daml
- src/test/daml/Daml/Finance/Bond/Test/ZeroCoupon.daml
- src/test/daml/Daml/Finance/Derivative/Test/Intermediated/BondCoupon.daml
Here is a first version of the tutorials related to bonds and other Contingent Claims based instruments.
Some open questions:
1. How/where do we explain the Contingent Claims part in more detail? 
2. Regarding bonds: What is the best way to link the tutorial to the more detailed specifications for bonds? Currently, I am thinking about linking to the auto-generated pages for Schedule / Daycount conventions / Bonds from the Bond Tutorial. Open to other suggestions as well.
> A first version of the tutorials

- docs/sphinx/theme/package.json
- docs/sphinx/theme/yarn.lock
The versions are now in line with https://github.com/digital-asset/daml/blob/main/package.json, which is what is effectively being used to build the main daml doc
> Update package.json for documentation

- package/main/daml/Daml.Finance.Interface.Instrument.Bond/daml.yaml
- package/main/daml/Daml.Finance.Interface.Instrument.Equity/daml.yaml
- package/main/daml/Daml.Finance.Interface.Instrument.Generic/daml.yaml
Couple of leftovers from the previous PR
> remove redundant dependencies

- src/main/daml/Daml/Finance/Common/Date/Schedule.daml
- src/test/daml/Daml/Finance/Common/Test/Date/Schedule.daml
I have added stubType to SchedulePeriod. This is useful / required for the ActAct daycount convention (and possibly others).
> add stubType to SchedulePeriod

- docs/source/demo-application/intro.rst
- docs/source/index.rst
- docs/source/packages/experimental-extensions.rst
- docs/source/tutorial/getting-started/download-daml-finance.rst
- docs/source/tutorial/getting-started/lifecycling.rst
- docs/source/tutorial/getting-started/settlement.rst
- docs/source/tutorial/getting-started/transfer.rst
- docs/source/tutorial/instrument-modelling/bond-extension.rst
- docs/source/tutorial/instrument-modelling/contingent-claims-instrument.rst
- docs/source/tutorial/instrument-modelling/contingent-claims-on-ledger-vs-on-the-fly.rst
- docs/source/tutorial/instrument-modelling/derivative-extension.rst
- src/main/daml/Daml/Finance/Instrument/Bond/FixedRate.daml
- src/main/daml/Daml/Finance/Instrument/Bond/FloatingRate.daml
- src/main/daml/Daml/Finance/Instrument/Bond/InflationLinked.daml
- src/main/daml/Daml/Finance/Instrument/Bond/Util.daml
- src/main/daml/Daml/Finance/Instrument/Bond/ZeroCoupon.daml
- src/main/daml/Daml/Finance/Interface/Instrument/Bond/FixedRate.daml
- src/main/daml/Daml/Finance/Interface/Instrument/Bond/FloatingRate.daml
- src/main/daml/Daml/Finance/Interface/Instrument/Bond/InflationLinked.daml
- src/main/daml/Daml/Finance/Interface/Instrument/Bond/ZeroCoupon.daml
This is a first attempt to document bonds at the package level. Not sure exactly which information belongs here, or how detailed it should be, so any feedback appreciated. 
I also did some minor improvements to the doc structure, including adding a section / placeholder for the Demo application.
> Update doc structure and describe bond package

- src/main/daml/Daml/Finance/Interface/Holding/Base.daml
- src/main/daml/Daml/Finance/Settlement/Batch.daml
- src/main/daml/Daml/Finance/Settlement/Instruction.daml
- src/test/daml/Daml/Finance/Holding/Test/Common.daml
> consistent holding template type rep per instrument and batch

- src/main/daml/Daml/Finance/Interface/Types/Date/DayCount.daml
- src/main/daml/Daml/Finance/Util/Date/DayCount.daml
- src/test/daml/Daml/Finance/Util/Test/Date/DayCount.daml
I have implemented the trivial 1/1 day-count convention.
> implement Basis_1_1 dcf

- src/main/daml/Daml/Finance/Holding/Fungible.daml
- src/main/daml/Daml/Finance/Holding/NonFungible.daml
- src/main/daml/Daml/Finance/Holding/Util.daml
- src/test/daml/Daml/Finance/Holding/Test/Fungible.daml
- src/test/daml/Daml/Finance/Holding/Test/NonFungible.daml
- src/test/daml/Daml/Finance/Holding/Test/Transfer.daml
Addresses https://github.com/DACH-NY/daml-finance/issues/338
> Transfers preserve existing locks

- docs/source/core-concepts.rst
- src/main/daml/Daml/Finance/Holding/Util.daml
I have expanded the section "Core concepts - Lifecycling" in the documentation.
https://github.com/DACH-NY/daml-finance/issues/337
> Document core concepts - lifecycling

- docs/source/packages/experimental-extensions.rst
- docs/source/packages/intro.rst
I have written a short package documentation for Equities. I also added some text to the Package Introduction section of the documentation.
> Write package documentation for Equities

- docs/source/packages/core-implementations.rst
- docs/source/packages/core-interfaces.rst
- src/main/daml/Daml/Finance/Interface/Lifecycle/Observable.daml
- src/main/daml/Daml/Finance/Interface/Lifecycle/Rule/Lifecycle.daml
- src/main/daml/Daml/Finance/Lifecycle/Effect.daml
- src/main/daml/Daml/Finance/Lifecycle/ElectionEffect.daml
- src/main/daml/Daml/Finance/Lifecycle/Event/Distribution.daml
- src/main/daml/Daml/Finance/Lifecycle/Event/Replacement.daml
- src/main/daml/Daml/Finance/Lifecycle/Rule/Distribution.daml
- src/main/daml/Daml/Finance/Lifecycle/Rule/Replacement.daml
I have written the package documentation for Lifecycle (interface and implementation).
> Package documentation for Lifecycle

- docs/source/packages/core-implementations.rst
- docs/source/packages/core-interfaces.rst
- src/main/daml/Daml/Finance/Interface/Types/Date/Calendar.daml
- src/main/daml/Daml/Finance/Interface/Types/Date/Classes.daml
- src/main/daml/Daml/Finance/RefData/Time/DateClock.daml
I have documented (what used to be called) the common packages: Util, Types and Refdata.
> Document common packages

- docs/source/packages/core-implementations.rst
- docs/source/packages/core-interfaces.rst
- src/main/daml/Daml/Finance/Settlement/Batch.daml
I have documented the settlement package, which was the last one remaining in the Package section of the documentation.
> Document the settlement package

- docs/code-samples/getting-started/daml.yaml
- docs/code-samples/getting-started/get-dependencies.sh
- docs/code-samples/getting-started/lib/.gitignore
- Changed `lib./`with `.lib/`;
- add command to create `.lib/` directory if it doesn't exist;
- fix incorrect curl commands (some copy/pasta that wasn't fully updated);
> Minor fixes for getting started

- src/main/daml/Daml/Finance/Interface/Holding/Account.daml
- src/main/daml/Daml/Finance/Interface/Holding/Util.daml
- src/main/daml/Daml/Finance/Interface/Util/Disclosure.daml
- src/main/daml/Daml/Finance/Lifecycle/Rule/Claim.daml
- src/main/daml/Daml/Finance/Settlement/Batch.daml
- src/main/daml/Daml/Finance/Settlement/Factory.daml
- src/main/daml/Daml/Finance/Settlement/Instruction.daml
- src/test/daml/Daml/Finance/Settlement/Test/Batch.daml
- src/test/daml/Daml/Finance/Settlement/Test/BatchWithIntermediaries.daml
- src/test/daml/Daml/Finance/Settlement/Test/Intermediated.daml
- src/test/daml/Daml/Finance/Settlement/Test/Transfer.daml
- src/test/daml/Daml/Finance/Test/Util/Holding.daml
> one disclosure context per Batch + trade id for Instruction + fix for RemoveObservers

- src/main/daml/Daml/Finance/Instrument/Swap/Currency.daml
- src/main/daml/Daml/Finance/Interface/Instrument/Swap/Currency.daml
- src/test/daml/Daml/Finance/Instrument/Bond/Test/FloatingRate.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/Currency.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/ForeignExchange.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/InterestRate.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/Util.daml
I have implemented a first version of currency swaps (fix vs fix payments in different currencies), as described here: https://github.com/digital-asset/daml-finance/issues/144
This could be done using only the existing contingent claims utility functions. Some improvements are still planned to those functions though, as described here: https://github.com/digital-asset/daml-finance/issues/149
> Implement currency swaps

- src/main/daml/Daml/Finance/Interface/Lifecycle/Effect.daml
- src/main/daml/Daml/Finance/Interface/Types/Common.daml
- src/main/daml/Daml/Finance/Lifecycle/Effect.daml
- src/main/daml/Daml/Finance/Lifecycle/ElectionEffect.daml
https://github.com/digital-asset/daml-finance/issues/147
> Add fields to the `Effect` interface

- src/main/daml/Daml/Finance/Instrument/Bond/FixedRate.daml
- src/main/daml/Daml/Finance/Instrument/Bond/FloatingRate.daml
- src/main/daml/Daml/Finance/Instrument/Bond/ZeroCoupon.daml
- src/main/daml/Daml/Finance/Instrument/Generic/Util.daml
- src/main/daml/Daml/Finance/Instrument/Swap/CreditDefault.daml
- src/main/daml/Daml/Finance/Instrument/Swap/Currency.daml
- src/main/daml/Daml/Finance/Instrument/Swap/ForeignExchange.daml
- src/main/daml/Daml/Finance/Instrument/Swap/InterestRate.daml
I have improved the contingent claims based utility functions that are shared between the Bond and the Swap instruments, as described here: https://github.com/digital-asset/daml-finance/issues/149
> Improve bond/swap utils

- docs/source/tutorials/instrument-modeling/bond-extension.rst
- docs/source/tutorials/instrument-modeling/bond-lifecycling.rst
- docs/source/tutorials/instrument-modeling/contingent-claims-instrument.rst
- docs/source/tutorials/instrument-modeling/derivative-extension.rst
- docs/source/tutorials/instrument-modeling/intro.rst
- docs/source/tutorials/instrument-modeling/swap-extension.rst
- package/main/daml/Daml.Finance.Instrument.Swap/daml.yaml
- src/main/daml/Daml/Finance/Instrument/Swap/CreditDefault/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Swap/ForeignExchange/Instrument.daml
- src/main/daml/Daml/Finance/Interface/Instrument/Swap/CreditDefault/Types.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/CreditDefault.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/Currency.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/ForeignExchange.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/InterestRate.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/Util.daml
I have written a tutorial for the Swap extension. I also improved a few comments in the swap package and fixed broken link in the docs.
> Write swap tutorial

- docs/source/concepts/lifecycling.rst
- docs/source/concepts/settlement.rst
- docs/source/overview/architecture.rst
- docs/source/overview/intro.rst
- docs/source/packages/core-implementations.rst
- docs/source/packages/core-interfaces.rst
- docs/source/packages/instrument-extensions.rst
- docs/source/packages/intro.rst
- docs/source/tutorials/getting-started/lifecycling.rst
- docs/source/tutorials/getting-started/settlement.rst
- docs/source/tutorials/getting-started/transfer.rst
- docs/source/tutorials/instrument-modeling/bond-extension.rst
- docs/source/tutorials/instrument-modeling/bond-lifecycling.rst
- docs/source/tutorials/instrument-modeling/contingent-claims-instrument.rst
- docs/source/tutorials/instrument-modeling/contingent-claims-on-ledger-vs-on-the-fly.rst
- docs/source/tutorials/instrument-modeling/derivative-extension.rst
- docs/source/tutorials/instrument-modeling/swap-extension.rst
Converts all titles (except FAQ questions) to title case, plus assorted edits in files not touched by other issues/prs.
[CHANGELOG_BEGIN]
[CHANGELOG_END]
> Converting Titles To Title Case

- src/main/daml/Daml/Finance/Holding/NonTransferable.daml
- src/main/daml/Daml/Finance/Interface/Lifecycle/Event/Distribution.daml
- src/main/daml/Daml/Finance/Interface/Lifecycle/Event/Replacement.daml
- src/main/daml/Daml/Finance/Interface/Lifecycle/Event/Time.daml
- src/main/daml/Daml/Finance/Lifecycle/Event/DateClock.daml
Also, remove redundant `AllowAmbiguousTypes`
> Fix typos in event interfaces

- src/test/daml/Daml/Finance/Data/Test/HolidayCalendar.daml
- src/test/daml/Daml/Finance/Holding/Test/Common.daml
- src/test/daml/Daml/Finance/Holding/Test/Fungible.daml
- src/test/daml/Daml/Finance/Holding/Test/NonFungible.daml
- src/test/daml/Daml/Finance/Holding/Test/NonTransferable.daml
- src/test/daml/Daml/Finance/Instrument/Bond/Test/FixedRate.daml
- src/test/daml/Daml/Finance/Instrument/Bond/Test/FloatingRate.daml
- src/test/daml/Daml/Finance/Instrument/Bond/Test/InflationLinked.daml
- src/test/daml/Daml/Finance/Instrument/Bond/Test/Util.daml
- src/test/daml/Daml/Finance/Instrument/Bond/Test/ZeroCoupon.daml
- src/test/daml/Daml/Finance/Instrument/Equity/Test/Dividend.daml
- src/test/daml/Daml/Finance/Instrument/Equity/Test/Merger.daml
- src/test/daml/Daml/Finance/Instrument/Equity/Test/StockSplit.daml
- src/test/daml/Daml/Finance/Instrument/Generic/Test/CallableBond.daml
- src/test/daml/Daml/Finance/Instrument/Generic/Test/EuropeanOption.daml
- src/test/daml/Daml/Finance/Instrument/Generic/Test/ForwardCash.daml
- src/test/daml/Daml/Finance/Instrument/Generic/Test/ForwardPhysical.daml
- src/test/daml/Daml/Finance/Instrument/Generic/Test/Intermediated/BondCoupon.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/Asset.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/CreditDefault.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/Currency.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/ForeignExchange.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/Fpml.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/InterestRate.daml
- src/test/daml/Daml/Finance/Settlement/Test/Batch.daml
- src/test/daml/Daml/Finance/Settlement/Test/BatchWithIntermediaries.daml
- src/test/daml/Daml/Finance/Settlement/Test/Intermediated.daml
- src/test/daml/Daml/Finance/Settlement/Test/Transfer.daml
- src/test/daml/Daml/Finance/Test/Util/Account.daml
Fixes https://github.com/digital-asset/daml-finance/issues/179
> Cleanup public party usage

- src/main/daml/Daml/Finance/Settlement/Batch.daml
- src/main/daml/Daml/Finance/Settlement/Instruction.daml
As mentioned to Johan yesterday, I am adding a couple of comments to the pass-through partial ordering for posterity's sake.
I also renamed a couple of functions with names that I find descriptive. Let me know what you think.
> Add comments to pass-through settlement

- src/main/daml/Daml/Finance/Interface/Claims/Util/Lifecycle.daml
Microscopic change, but Johan reminded me last Thursday that we have `foldlA` in the Action module
> use `foldlA` in util function

- docs/source/packages/instrument-extensions.rst
- docs/source/tutorials/instrument-modeling/swap-extension.rst
- src/test/daml/Daml/Finance/Instrument/Swap/Test/Fpml.daml
I have written some initial documentation of the FpML swaps, as specified here: https://github.com/digital-asset/daml-finance/issues/260
> Write basic FpML swap documentation

- src/main/daml/Daml/Finance/Instrument/Swap/Fpml/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Swap/Fpml/Util.daml
I have done a minor change to improve the handling of stub rate used for fixed rate legs, as specified here: https://github.com/digital-asset/daml-finance/issues/266
> Improve handling of stub periods for FpML swaps

- src/main/daml/Daml/Finance/Instrument/Generic/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Generic/Util.daml
- src/main/daml/Daml/Finance/Interface/Lifecycle/Effect.daml
- src/main/daml/Daml/Finance/Lifecycle/Effect.daml
- src/main/daml/Daml/Finance/Lifecycle/ElectionEffect.daml
- src/main/daml/Daml/Finance/Lifecycle/Rule/Distribution.daml
- src/main/daml/Daml/Finance/Lifecycle/Rule/Replacement.daml
- src/test/daml/Daml/Finance/Instrument/Bond/Test/Util.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/Util.daml
Let me know what you think, I find this more descriptive.
> Rename consumed (produced) to otherConsumed (otherProduced)

- src/main/daml/Daml/Finance/Lifecycle/Rule/Claim.daml
- src/test/daml/Daml/Finance/Instrument/Equity/Test/Dividend.daml
- src/test/daml/Daml/Finance/Instrument/Equity/Test/Merger.daml
- src/test/daml/Daml/Finance/Instrument/Equity/Test/StockSplit.daml
- src/test/daml/Daml/Finance/Instrument/Generic/Test/CallableBond.daml
- src/test/daml/Daml/Finance/Instrument/Generic/Test/EuropeanOption.daml
- src/test/daml/Daml/Finance/Instrument/Generic/Test/ForwardCash.daml
- src/test/daml/Daml/Finance/Instrument/Generic/Test/Intermediated/BondCoupon.daml
> Reduce signatory constraints on `Claim.Rule`

- src/main/daml/Daml/Finance/Instrument/Swap/Fpml/Util.daml
- src/main/daml/Daml/Finance/Interface/Instrument/Swap/Fpml/FpmlTypes.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/Fpml.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/Util.daml
I have implemented exchange of principal, as described here: https://github.com/digital-asset/daml-finance/issues/312
This is the last remaining feature we need for the sample trades received so far.
> Principal exchange for FpML Swaps

- docs/source/packages/instrument-extensions.rst
- docs/source/tutorials/instrument-modeling/bond-lifecycling.rst
- docs/source/tutorials/instrument-modeling/contingent-claims-on-ledger-vs-on-the-fly.rst
- docs/source/tutorials/instrument-modeling/generic-extension.rst
- docs/source/tutorials/instrument-modeling/intro.rst
Here are a few improvements to the instrument modelling tutorials.
> Improve the instrument modelling tutorials

- src/main/daml/Daml/Finance/Instrument/Bond/FixedRate/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Bond/FloatingRate/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Bond/InflationLinked/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Bond/ZeroCoupon/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Swap/Asset/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Swap/CreditDefault/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Swap/Currency/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Swap/ForeignExchange/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Swap/Fpml/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Swap/InterestRate/Instrument.daml
- src/main/daml/Daml/Finance/Interface/Instrument/Bond/FixedRate/Types.daml
- src/main/daml/Daml/Finance/Interface/Instrument/Bond/FloatingRate/Types.daml
- src/main/daml/Daml/Finance/Interface/Instrument/Bond/InflationLinked/Types.daml
- src/main/daml/Daml/Finance/Interface/Instrument/Bond/ZeroCoupon/Types.daml
- src/main/daml/Daml/Finance/Interface/Instrument/Swap/Asset/Types.daml
- src/main/daml/Daml/Finance/Interface/Instrument/Swap/CreditDefault/Types.daml
- src/main/daml/Daml/Finance/Interface/Instrument/Swap/Currency/Types.daml
- src/main/daml/Daml/Finance/Interface/Instrument/Swap/InterestRate/Types.daml
As a preparation for the upcoming release, here are several minor improvements to the bond/swap codebase, mainly concerning comments of the template (and interface) variables.
> Improve bond/swap code

- docs/source/packages/instrument-extensions.rst
- docs/source/tutorials/instrument-modeling/bond-extension.rst
- src/test/daml/Daml/Finance/Instrument/Bond/Test/FloatingRate.daml
- src/test/daml/Daml/Finance/Instrument/Bond/Test/Util.daml
This is a small PR to improve the package documentation for bond and swaps. 
It also adds a few minor improvements to the bond tutorial, including the underlying test code.
> Improve bond/swap docs

- .circleci/config.yml
https://github.com/digital-asset/daml-finance/issues/134
> Add title to releases to avoid having the last commit message as part of the release title

- docs/source/tutorials/instrument-modeling/contingent-claims-instrument.rst
- src/main/daml/Daml/Finance/Claims/Lifecycle/Rule.daml
- src/main/daml/Daml/Finance/Instrument/Bond/FixedRate/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Bond/FloatingRate/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Bond/InflationLinked/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Bond/ZeroCoupon/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Swap/Asset/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Swap/CreditDefault/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Swap/Currency/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Swap/ForeignExchange/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Swap/Fpml/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Swap/InterestRate/Instrument.daml
- src/main/daml/Daml/Finance/Interface/Claims/Dynamic/Instrument.daml
… after rule separation
Fixes https://github.com/digital-asset/daml-finance/issues/396
Fixes https://github.com/digital-asset/daml-finance/issues/401
> Adjust Contingent Claims instrument tutorial and rename NewVersion interface

- docs/source/overview/architecture.rst
- docs/source/overview/building-applications.rst
- docs/source/overview/extending-daml-finance.rst
- docs/source/overview/intro.rst
Fixes https://github.com/digital-asset/daml-finance/issues/417
> Review/improve the Overview section of the docs

- docs/source/concepts/asset-model.rst
A few minor changes, mainly adding references to other parts of the docs.
> Update Asset Model doc

- docs/source/reference/glossary.rst
> remove confusing terms from glossary

- docs/source/concepts/settlement.rst
- src/main/daml/Daml/Finance/Interface/Settlement/Types.daml
Added references to other parts of the docs and did some minor changes.
> update Settlement docs

- docs/source/concepts/contingent-claims.rst
- src/main/daml/ContingentClaims/Core/Internal/Claim.daml
- src/main/daml/ContingentClaims/Lifecycle/Lifecycle.daml
- src/test/daml/ContingentClaims/Test/FinancialContract.daml
- Added references to the rest of the docs
- Minor changes to wording
- Replaced a couple of verbatim code blocks by references to the codebase
Fixes https://github.com/digital-asset/daml-finance/issues/422
> update Contingent Claims docs

- docs/source/packages/interfaces/contingent-claims-core.rst
- docs/source/packages/interfaces/daml-finance-interface-account.rst
- docs/source/packages/interfaces/daml-finance-interface-data.rst
- docs/source/packages/interfaces/daml-finance-interface-holding.rst
- docs/source/packages/interfaces/daml-finance-interface-instrument-base.rst
- docs/source/packages/interfaces/daml-finance-interface-instrument-equity.rst
- docs/source/packages/interfaces/daml-finance-interface-instrument-token.rst
- docs/source/packages/interfaces/daml-finance-interface-lifecycle.rst
- docs/source/packages/interfaces/daml-finance-interface-settlement.rst
- docs/source/packages/interfaces/index.rst
- src/main/daml/Daml/Finance/Interface/Instrument/Bond/FixedRate/Factory.daml
- src/main/daml/Daml/Finance/Interface/Instrument/Bond/FloatingRate/Factory.daml
- src/main/daml/Daml/Finance/Interface/Instrument/Bond/InflationLinked/Factory.daml
- src/main/daml/Daml/Finance/Interface/Instrument/Bond/ZeroCoupon/Factory.daml
- src/main/daml/Daml/Finance/Interface/Instrument/Equity/Factory.daml
- src/main/daml/Daml/Finance/Interface/Instrument/Generic/Factory.daml
- src/main/daml/Daml/Finance/Interface/Instrument/Swap/Asset/Factory.daml
- src/main/daml/Daml/Finance/Interface/Instrument/Swap/CreditDefault/Factory.daml
- src/main/daml/Daml/Finance/Interface/Instrument/Swap/Currency/Factory.daml
- src/main/daml/Daml/Finance/Interface/Instrument/Swap/ForeignExchange/Factory.daml
- src/main/daml/Daml/Finance/Interface/Instrument/Swap/Fpml/Factory.daml
- src/main/daml/Daml/Finance/Interface/Instrument/Swap/InterestRate/Factory.daml
- src/main/daml/Daml/Finance/Interface/Instrument/Token/Factory.daml
- src/main/daml/Daml/Finance/Interface/Instrument/Token/Instrument.daml
- src/main/daml/Daml/Finance/Interface/Lifecycle/Rule/Lifecycle.daml
- Fix incorrect references
- Align code comments with documentation
- Minor updates to wording
> update Interface Packages docs

- docs/source/tutorials/getting-started/intro.rst
- docs/source/tutorials/getting-started/transfer.rst
- add references to other parts of the docs
- minor changes to wording
> update the Quickstart and Transfer tutorials

- docs/source/tutorials/getting-started/lifecycling.rst
- docs/source/tutorials/getting-started/settlement.rst
- added a few references
- corrected (switched) Alice and Bob in one example
- removed example that Generic implements lifecycling on the instrument itself
- minor changes of wording
> update Settlement and Lifecycling tutorials

- docs/source/concepts/asset-model.rst
- docs/source/overview/index.rst
- docs/source/reference/index.rst
- docs/source/tutorials/index.rst
Also some minor changes to the concepts section.
Fixes https://github.com/digital-asset/daml-finance/issues/457
> Include a short description of each section in the docs.

- src/main/daml/Daml/Finance/Interface/Lifecycle/Rule/Claim.daml
- src/main/daml/Daml/Finance/Interface/Settlement/Factory.daml
- src/main/daml/Daml/Finance/Lifecycle/Rule/Claim.daml
- src/main/daml/Daml/Finance/Settlement/Factory.daml
- src/test/daml/Daml/Finance/Settlement/Test/Batch.daml
- src/test/daml/Daml/Finance/Settlement/Test/BatchWithIntermediaries.daml
- src/test/daml/Daml/Finance/Settlement/Test/Intermediated.daml
- src/test/daml/Daml/Finance/Settlement/Test/Transfer.daml
In order to be consistent with the rest of factories
> Use `F` instead of `I` for Settlement Factory

- docs/source/tutorials/instrument-modeling/equity-extension.rst
- src/test/daml/Daml/Finance/Instrument/Equity/Test/Dividend.daml
- Write a test case for an equity bonus issue (giving out new shares)
- Describe this in the Equity Tutorial as well.
- In the tutorial, also describe what change is needed to give out warrants instead of stocks.
Fixes https://github.com/digital-asset/daml-finance/issues/492
> Test/document Equity Bonus Issue

- docs/source/tutorials/instrument-modeling/equity-extension.rst
- src/test/daml/Daml/Finance/Instrument/Equity/Test/Dividend.daml
- Add dividend options to the dividend test
- Verify that double spending is not possible
- Describe how dividend options work in the Equity tutorial
Fixes https://github.com/digital-asset/daml-finance/issues/500
> Implement and document dividend options

- src/main/daml/Daml/Finance/Instrument/Swap/Fpml/Util.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/Fpml.daml
- Implement the different rounding methods defined in the FpML swap standard.
- Add unit tests for rounding direction and precision.
> Implement rate rounding functionality required for FpML swaps

- src/main/daml/Daml/Finance/Instrument/Swap/Fpml/Util.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/Fpml.daml
- Implement spread-exclusive compounding
- Implement flat compounding
- Simplify and reuse code by merging compounding logic into `calculateFloatingPaymentClaimsFromSwapStream`
- Add test cases
> Implement rate compounding methods for FpML swaps

- src/main/daml/Daml/Finance/Instrument/Swap/Fpml/Util.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/Fpml.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/Util.daml
- Add new sample trade
- Implement support for principal exchange for fix leg
- Make sure exchange of principal works also when there is no intermediate exchange (only initial and final).
> Add FpML sample trade 6 and improve logic for exchange of principal

- package/main/daml/Daml.Finance.Instrument.Option/README.md
- package/main/daml/Daml.Finance.Instrument.Option/daml.yaml
- package/main/daml/Daml.Finance.Instrument.Option/daml/Daml/Finance/Instrument/Option
- package/main/daml/Daml.Finance.Interface.Instrument.Option/README.md
- package/main/daml/Daml.Finance.Interface.Instrument.Option/daml.yaml
- package/main/daml/Daml.Finance.Interface.Instrument.Option/daml/Daml/Finance/Interface/Instrument/Option
- package/packages.yaml
- package/test/daml/Daml.Finance.Instrument.Option.Test/daml.yaml
- package/test/daml/Daml.Finance.Instrument.Option.Test/daml/Daml/Finance/Instrument/Option/Test
- src/main/daml/Daml/Finance/Claims/Util/Builders.daml
- src/main/daml/Daml/Finance/Instrument/Option/European/Factory.daml
- src/main/daml/Daml/Finance/Instrument/Option/European/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Option/Util.daml
- src/main/daml/Daml/Finance/Interface/Instrument/Option/European/Factory.daml
- src/main/daml/Daml/Finance/Interface/Instrument/Option/European/Instrument.daml
- src/main/daml/Daml/Finance/Interface/Instrument/Option/European/Types.daml
- src/test/daml/Daml/Finance/Instrument/Option/Test/European.daml
- src/test/daml/Daml/Finance/Instrument/Option/Test/Util.daml
Including a first option type: cash settled automatically exercised European options (using Cond).
Fixes https://github.com/digital-asset/daml-finance/issues/593
> Create new Option package

- src/main/daml/Daml/Finance/Interface/Settlement/Factory.daml
I would like to release this as part of the new doc assembly.
I am currently having a hard time convincing Packell that this does not require a package bump 😓 
Packell PR: https://github.com/digital-asset/daml-finance/pull/627
> Fix typo in Settlement Factory documentation

- CHANGELOG.md
- src/main/daml/Daml/Finance/Claims/Util/Builders.daml
- src/main/daml/Daml/Finance/Instrument/Option/EuropeanCash/Factory.daml
- src/main/daml/Daml/Finance/Instrument/Option/EuropeanCash/Instrument.daml
- src/main/daml/Daml/Finance/Interface/Instrument/Option/EuropeanCash/Factory.daml
- src/main/daml/Daml/Finance/Interface/Instrument/Option/EuropeanCash/Instrument.daml
- src/main/daml/Daml/Finance/Interface/Instrument/Option/EuropeanCash/Types.daml
- src/test/daml/Daml/Finance/Instrument/Option/Test/EuropeanCash.daml
- src/test/daml/Daml/Finance/Instrument/Option/Test/Util.daml
Fixes https://github.com/digital-asset/daml-finance/issues/659
> Rename European cash-settled options

- package/packages.yaml
- package/test/daml/Daml.Finance.Instrument.Equity.Test/daml.yaml
- src/main/daml/Daml/Finance/Claims/Util/Builders.daml
- src/main/daml/Daml/Finance/Instrument/Option/EuropeanPhysical/Instrument.daml
- src/test/daml/Daml/Finance/Instrument/Equity/Test/RightsIssue.daml
- src/test/daml/Daml/Finance/Instrument/Option/Test/EuropeanCash.daml
- src/test/daml/Daml/Finance/Instrument/Option/Test/EuropeanPhysical.daml
- src/test/daml/Daml/Finance/Instrument/Option/Test/Util.daml
- Fix claim util function to support both long and short options
- Add tests for this to both `EuropeanCash` and `EuropeanPhysical`
- Add scenario for rights issue and subscription, using `EuropeanPhysical`
Fixes https://github.com/digital-asset/daml-finance/issues/597
> Rights issue and subscription

- src/main/daml/Daml/Finance/Claims/Util/Builders.daml
- src/main/daml/Daml/Finance/Instrument/Option/Dividend/Factory.daml
- src/main/daml/Daml/Finance/Instrument/Option/Dividend/Instrument.daml
- src/main/daml/Daml/Finance/Interface/Instrument/Option/Dividend/Types.daml
- src/test/daml/Daml/Finance/Instrument/Option/Test/Dividend.daml
- src/test/daml/Daml/Finance/Instrument/Option/Test/Util.daml
Fixes https://github.com/digital-asset/daml-finance/issues/700
> Remove isLong from Dividend option

- src/main/daml/Daml/Finance/Claims/Util/Builders.daml
- src/test/daml/Daml/Finance/Instrument/Equity/Test/RightsIssue.daml
- src/test/daml/Daml/Finance/Instrument/Option/Test/EuropeanPhysical.daml
- src/test/daml/Daml/Finance/Instrument/Option/Test/Util.daml
Fixes https://github.com/digital-asset/daml-finance/issues/703
> Fix short option claim

- CHANGELOG.md
- daml.yaml
- src/test/daml/Daml/Finance/Instrument/Equity/Test/DivOption.daml
- src/test/daml/Daml/Finance/Instrument/Option/Test/Dividend.daml
- src/test/daml/Daml/Finance/Instrument/Option/Test/Util.daml
Fixes https://github.com/digital-asset/daml-finance/issues/715
> Prepare for dividend option documentation

- src/test/daml/Daml/Finance/Instrument/Generic/Test/Intermediated/BondCoupon.daml
https://discuss.daml.com/t/bondcoupon-test-probable-wrong-csd-description-in-testparties-data-type/6325
> Fix description of parties in `BondCoupon` test

- daml.yaml
- src/main/daml/Daml/Finance/Instrument/Bond/Callable/Factory.daml
- src/main/daml/Daml/Finance/Instrument/Bond/Callable/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Bond/Util.daml
- src/main/daml/Daml/Finance/Interface/Instrument/Bond/Callable/Types.daml
- src/test/daml/Daml/Finance/Instrument/Bond/Test/Callable.daml
- src/test/daml/Daml/Finance/Instrument/Bond/Test/Util.daml
- src/test/daml/Daml/Finance/Test/Util/Instrument.daml
Fixes https://github.com/digital-asset/daml-finance/issues/736
> Coupon floor / cap on a callable bond

- src/main/daml/Daml/Finance/Interface/Instrument/Equity/Factory.daml
- src/main/daml/Daml/Finance/Interface/Instrument/Option/Dividend/Election/Factory.daml
- src/main/daml/Daml/Finance/Interface/Instrument/Token/Factory.daml
- src/main/daml/Daml/Finance/Interface/Lifecycle/Election/Factory.daml
Fixes https://github.com/digital-asset/daml-finance/issues/692
> Fix interface comments

- src/main/daml/Daml/Finance/Claims/Lifecycle/Rule.daml
- src/main/daml/Daml/Finance/Instrument/Bond/Util.daml
- src/test/daml/Daml/Finance/Instrument/Bond/Test/Callable.daml
- src/test/daml/Daml/Finance/Instrument/Bond/Test/Util.daml
- src/test/daml/Daml/Finance/Instrument/Option/Test/Util.daml
Fixes https://github.com/digital-asset/daml-finance/issues/776
Fixes https://github.com/digital-asset/daml-finance/issues/773
Fixes https://github.com/digital-asset/daml-finance/issues/778
> Implement support for hybrid (election & time-based) instruments

- src/main/daml/Daml/Finance/Claims/Util/Builders.daml
- src/main/daml/Daml/Finance/Instrument/Bond/Util.daml
- src/main/daml/Daml/Finance/Instrument/Option/Dividend/Election.daml
- src/main/daml/Daml/Finance/Lifecycle/Election.daml
- src/test/daml/Daml/Finance/Instrument/Bond/Test/Callable.daml
- src/test/daml/Daml/Finance/Instrument/Bond/Test/FixedRate.daml
- src/test/daml/Daml/Finance/Instrument/Bond/Test/FloatingRate.daml
- src/test/daml/Daml/Finance/Instrument/Bond/Test/InflationLinked.daml
- src/test/daml/Daml/Finance/Instrument/Bond/Test/ZeroCoupon.daml
- src/test/daml/Daml/Finance/Instrument/Option/Test/Dividend.daml
- src/test/daml/Daml/Finance/Instrument/Option/Test/EuropeanCash.daml
- src/test/daml/Daml/Finance/Instrument/Option/Test/EuropeanPhysical.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/Asset.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/Currency.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/ForeignExchange.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/Fpml.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/InterestRate.daml
Fixes https://github.com/digital-asset/daml-finance/issues/719
> Remove Cid from reference names

- src/main/daml/Daml/Finance/Claims/Lifecycle/Rule.daml
Fixes https://github.com/digital-asset/daml-finance/issues/752
> Create version consisting of more than hash of remaining claims

- daml.yaml
- src/main/daml/Daml/Finance/Instrument/Bond/Util.daml
- src/main/daml/Daml/Finance/Interface/Instrument/Bond/Callable/BondTypes.daml
- src/test/daml/Daml/Finance/Instrument/Bond/Test/Callable.daml
- src/test/daml/Daml/Finance/Test/Util/Lifecycle.daml
Fixes https://github.com/digital-asset/daml-finance/issues/786
Fixes https://github.com/digital-asset/daml-finance/issues/765
> Add support for SOFR rate for callable bonds using ObserveAt

- daml.yaml
- src/main/daml/Daml/Finance/Instrument/Bond/Callable/Instrument.daml
- src/test/daml/Daml/Finance/Instrument/Bond/Test/Callable.daml
Fixes https://github.com/digital-asset/daml-finance/issues/794
> Improve callable bond docs

- daml.yaml
- src/main/daml/Daml/Finance/Instrument/Bond/Callable/Factory.daml
- src/main/daml/Daml/Finance/Instrument/Bond/Callable/Instrument.daml
- src/main/daml/Daml/Finance/Interface/Instrument/Bond/Callable/Types.daml
- src/test/daml/Daml/Finance/Instrument/Bond/Test/Callable.daml
- src/test/daml/Daml/Finance/Instrument/Bond/Test/Util.daml
Fixes https://github.com/digital-asset/daml-finance/issues/801
> Make adjusted dates configurable for Callable Bond dcfs

- src/main/daml/Daml/Finance/Instrument/Bond/Util.daml
- src/test/daml/Daml/Finance/Instrument/Bond/Test/Callable.daml
Fixes https://github.com/digital-asset/daml-finance/issues/810
> Improve treatment of Following Unadjusted for callable bonds

- src/main/daml/Daml/Finance/Instrument/Swap/Fpml/Util.daml
Solves parts of https://github.com/digital-asset/daml-finance/issues/792
> Refactor FpML swaps using ObserveAt

- src/main/daml/Daml/Finance/Claims/Util/Builders.daml
- src/main/daml/Daml/Finance/Instrument/Swap/Fpml/Util.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/Fpml.daml
Solves parts of https://github.com/digital-asset/daml-finance/issues/792
> Use ObserveAt in the remaining FpML swap util functions

- src/test/daml/Daml/Finance/Instrument/Equity/Test/DivOption.daml
- src/test/daml/Daml/Finance/Instrument/Option/Test/Dividend.daml
- src/test/daml/Daml/Finance/Instrument/Option/Test/Util.daml
Fixes https://github.com/digital-asset/daml-finance/issues/711
> Align DivOption test roles with other election tests

- src/test/daml/Daml/Finance/Instrument/Option/Test/Util.daml
- src/test/daml/Daml/Finance/Test/Util/Lifecycle.daml
Fixes https://github.com/digital-asset/daml-finance/issues/821
> Reuse code between DivOptions and other other instruments

- package/main/daml/Daml.Finance.Instrument.Option/daml.yaml
- src/main/daml/Daml/Finance/Instrument/Option/Dividend/Election.daml
Fixes https://github.com/digital-asset/daml-finance/issues/824
> Reuse Election for DivOptions

- daml.yaml
- docs/code-samples/getting-started/daml/Scripts/Holding.daml
- docs/code-samples/getting-started/daml/Scripts/Transfer.daml
Fixes https://github.com/digital-asset/daml-finance/issues/838
> Create a Holding script for the Getting Started tutorial

- src/test/daml/Daml/Finance/Instrument/Equity/Test/RightsIssue.daml
Fixes https://github.com/digital-asset/daml-finance/issues/840
> Change Rights Issue test to use investorAccount for short option

- src/main/daml/Daml/Finance/Interface/Types/Common/Types.daml
- src/main/daml/Daml/Finance/Interface/Util/Disclosure.daml
Fixes https://github.com/digital-asset/daml-finance/issues/737
> Describe PartiesMap in the disclosure interface

- CHANGELOG.md
- src/main/daml/ContingentClaims/Core/Claim.daml
- src/main/daml/Daml/Finance/Claims/Util/Builders.daml
- src/main/daml/Daml/Finance/Instrument/Swap/Fpml/Util.daml
- src/test/daml/Daml/Finance/Instrument/Generic/Test/Intermediated/BondCoupon.daml
Fixes https://github.com/digital-asset/daml-finance/issues/698
> Add list version of and cc smart constructor

- CHANGELOG.md
- package/main/daml/Daml.Finance.Lifecycle/daml.yaml
- src/main/daml/Daml/Finance/Lifecycle/Rule/Distribution.daml
- src/main/daml/Daml/Finance/Lifecycle/Rule/Replacement.daml
Fixes https://github.com/digital-asset/daml-finance/issues/579
> Extra check for Evolve

- CHANGELOG.md
- src/main/daml/Daml/Finance/Claims/Lifecycle/Rule.daml
- src/main/daml/Daml/Finance/Instrument/Generic/Lifecycle/Rule.daml
- src/main/daml/Daml/Finance/Lifecycle/Effect.daml
- src/main/daml/Daml/Finance/Lifecycle/ElectionEffect.daml
- src/main/daml/Daml/Finance/Lifecycle/Rule/Distribution.daml
- src/main/daml/Daml/Finance/Lifecycle/Rule/Replacement.daml
Fixes https://github.com/digital-asset/daml-finance/issues/793
> Let the Effect implement the Disclosure interface

- src/main/daml/Daml/Finance/Interface/Instrument/Base/Instrument.daml
- src/main/daml/Daml/Finance/Interface/Lifecycle/Effect.daml
- src/main/daml/Daml/Finance/Lifecycle/Effect.daml
Relates to https://github.com/digital-asset/daml-finance/issues/263
> Document user questions

- docs/code-samples/getting-started/daml.yaml
- docs/code-samples/getting-started/daml.yaml.template
- docs/code-samples/getting-started/daml/Scripts/Lifecycling.daml
- docs/code-samples/getting-started/daml/Scripts/Settlement.daml
> use instrument factories in quickstarter

- src/main/daml/Daml/Finance/Claims/Lifecycle/Rule.daml
Fixes https://github.com/digital-asset/daml-finance/issues/910
> Indicate that election error can be due to tag or time

- src/main/daml/Daml/Finance/Instrument/Bond/Callable/Factory.daml
- src/test/daml/Daml/Finance/Instrument/Bond/Test/Callable.daml
- src/test/daml/Daml/Finance/Instrument/Bond/Test/Util.daml
Relates to https://github.com/digital-asset/daml-finance/issues/753
> Validate schedule on bond creation

- CHANGELOG.md
- src/main/daml/Daml/Finance/Interface/Lifecycle/Effect.daml
- src/main/daml/Daml/Finance/Lifecycle/Effect.daml
- src/main/daml/Daml/Finance/Lifecycle/ElectionEffect.daml
- src/main/daml/Daml/Finance/Lifecycle/Rule/Claim.daml
[367](https://github.com/digital-asset/daml-finance/issues/367)
> Changed the arguments for the Calculate choice of the Effect.I

- docs/code-samples/lifecycling/daml/Scripts/CallableBond.daml
- docs/code-samples/lifecycling/daml/Scripts/FixedRateBond.daml
Fixes https://github.com/digital-asset/daml-finance/issues/904
> Callable bond e2e script (to demonstrate Elections)

- src/test/daml/Daml/Finance/Data/Test/HolidayCalendar.daml
- src/test/daml/Daml/Finance/Instrument/Bond/Test/Callable.daml
- src/test/daml/Daml/Finance/Instrument/Bond/Test/FixedRate.daml
- src/test/daml/Daml/Finance/Instrument/Bond/Test/FloatingRate.daml
- src/test/daml/Daml/Finance/Instrument/Bond/Test/InflationLinked.daml
- src/test/daml/Daml/Finance/Instrument/Bond/Test/Util.daml
- src/test/daml/Daml/Finance/Instrument/StructuredProduct/Test/BarrierReverseConvertible.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/Asset.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/Currency.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/Fpml.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/InterestRate.daml
- src/test/daml/Daml/Finance/Util/Test/Date/Calendar.daml
Relates to https://github.com/digital-asset/daml-finance/issues/753
> Add negative test for callable bond validation

- package/test/daml/Daml.Finance.Instrument.StructuredProduct.Test/daml.yaml
- src/test/daml/Daml/Finance/Instrument/Bond/Test/Callable.daml
- src/test/daml/Daml/Finance/Instrument/Bond/Test/FixedRate.daml
- src/test/daml/Daml/Finance/Instrument/Bond/Test/FloatingRate.daml
- src/test/daml/Daml/Finance/Instrument/Bond/Test/InflationLinked.daml
- src/test/daml/Daml/Finance/Instrument/Bond/Test/Util.daml
- src/test/daml/Daml/Finance/Instrument/Bond/Test/ZeroCoupon.daml
- src/test/daml/Daml/Finance/Instrument/Equity/Test/DivOption.daml
- src/test/daml/Daml/Finance/Instrument/Equity/Test/RightsIssue.daml
- src/test/daml/Daml/Finance/Instrument/Option/Test/BarrierEuropeanCash.daml
- src/test/daml/Daml/Finance/Instrument/Option/Test/Dividend.daml
- src/test/daml/Daml/Finance/Instrument/Option/Test/EuropeanCash.daml
- src/test/daml/Daml/Finance/Instrument/Option/Test/EuropeanPhysical.daml
- src/test/daml/Daml/Finance/Instrument/Option/Test/Util.daml
- src/test/daml/Daml/Finance/Instrument/StructuredProduct/Test/BarrierReverseConvertible.daml
- src/test/daml/Daml/Finance/Instrument/StructuredProduct/Test/Util.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/Asset.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/CreditDefault.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/Currency.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/ForeignExchange.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/Fpml.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/InterestRate.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/Util.daml
Fixes https://github.com/digital-asset/daml-finance/issues/922
> Create dynamic instruments using factories

- docs/code-samples/lifecycling/daml/Scripts/FixedRateBond.daml
Fixes https://github.com/digital-asset/daml-finance/issues/918
> Reduce the use of submitMulti in lifecycling e2e tests

- src/main/daml/Daml/Finance/Instrument/Bond/FixedRate/Factory.daml
- src/main/daml/Daml/Finance/Instrument/Bond/FloatingRate/Factory.daml
- src/main/daml/Daml/Finance/Instrument/Bond/InflationLinked/Factory.daml
- src/main/daml/Daml/Finance/Instrument/Bond/ZeroCoupon/Factory.daml
- src/main/daml/Daml/Finance/Instrument/Option/BarrierEuropeanCash/Factory.daml
- src/main/daml/Daml/Finance/Instrument/Option/Dividend/Factory.daml
- src/main/daml/Daml/Finance/Instrument/Option/EuropeanCash/Factory.daml
- src/main/daml/Daml/Finance/Instrument/Option/EuropeanPhysical/Factory.daml
- src/main/daml/Daml/Finance/Instrument/StructuredProduct/BarrierReverseConvertible/Factory.daml
- src/main/daml/Daml/Finance/Instrument/Swap/Asset/Factory.daml
- src/main/daml/Daml/Finance/Instrument/Swap/CreditDefault/Factory.daml
- src/main/daml/Daml/Finance/Instrument/Swap/Currency/Factory.daml
- src/main/daml/Daml/Finance/Instrument/Swap/ForeignExchange/Factory.daml
- src/main/daml/Daml/Finance/Instrument/Swap/Fpml/Factory.daml
- src/main/daml/Daml/Finance/Instrument/Swap/InterestRate/Factory.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/CreditDefault.daml
Fixes https://github.com/digital-asset/daml-finance/issues/753
> Validate remaining dynamic instruments

- daml.yaml
- docs/code-samples/lifecycling/daml/Scripts/CallableBond.daml
- docs/code-samples/lifecycling/daml/Scripts/FixedRateBond.daml
- docs/code-samples/lifecycling/daml/Scripts/FloatingRateBond.daml
> Lifecycling e2e updates

- CHANGELOG.md
- src/main/daml/Daml/Finance/Settlement/Factory.daml
- src/main/daml/Daml/Finance/Util/Common.daml
- src/test/daml/Daml/Finance/Settlement/Test/Transfer.daml
+ amended order in settlement factory
fixes https://github.com/digital-asset/daml-finance/issues/943
> removed mapWithIndex (which applied the index in reverse order) 

- CHANGELOG.md
- src/main/daml/Daml/Finance/Settlement/Batch.daml
- src/main/daml/Daml/Finance/Util/Common.daml
- src/test/daml/Daml/Finance/Util/Test/Common.daml
fixes https://github.com/digital-asset/daml-finance/issues/942
> order settledCids in batch

- docs/code-samples/getting-started/daml/Scripts/Holding.daml
- docs/code-samples/getting-started/daml/Scripts/Lifecycling.daml
- docs/code-samples/getting-started/daml/Scripts/Settlement.daml
- docs/code-samples/getting-started/daml/Scripts/Transfer.daml
A few changes with the hope to make the getting started tutorial simpler
- use explicit observers instead of public party
- always use factories to create instruments, holdings
- minor changes to comments / structure
> Refactor getting started scripts

- CHANGELOG.md
https://github.com/digital-asset/daml-finance/issues/955
> Polish changelog for `2.7`

- docs/code-samples/getting-started/README.md
- docs/code-samples/lifecycling/README.md
- docs/code-samples/payoff-modeling/README.md
- docs/code-samples/payoff-modeling/daml.yaml
- docs/code-samples/payoff-modeling/daml.yaml.template
- docs/code-samples/payoff-modeling/daml/Examples/BasicCombinators.daml
- docs/code-samples/payoff-modeling/daml/PayoffBuilder.daml
- docs/code-samples/payoff-modeling/daml/Util.daml
- docs/code-samples/payoff-modeling/daml/Util/Lifecycle.daml
- docs/code-samples/payoff-modeling/daml/Util/Setup.daml
- docs/code-samples/payoff-modeling/get-dependencies.bat
- docs/code-samples/payoff-modeling/get-dependencies.sh
https://github.com/digital-asset/daml-finance/issues/797
https://github.com/digital-asset/daml-finance/issues/755
https://github.com/digital-asset/daml-finance/issues/608
fixes https://github.com/digital-asset/daml-finance/issues/939
> Add payoff modelling tutorial

- docs/code-samples/README.md
- docs/code-samples/getting-started-config/README.md
All code samples must be tested with `daml start` in addition to `daml test`
> Improve code samples README

- CHANGELOG.md
- src/main/daml/Daml/Finance/Holding/Util.daml
https://github.com/digital-asset/daml-finance/issues/992
> Fix for transfer (custodian of outgoing and incoming account must match)

- src/main/daml/Daml/Finance/Account/Account.daml
- src/main/daml/Daml/Finance/Data/Time/DateClock.daml
- src/main/daml/Daml/Finance/Instrument/Bond/Callable/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Bond/FixedRate/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Bond/FloatingRate/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Bond/InflationLinked/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Bond/ZeroCoupon/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Equity/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Generic/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Option/BarrierEuropeanCash/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Option/Dividend/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Option/EuropeanCash/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Option/EuropeanPhysical/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/StructuredProduct/BarrierReverseConvertible/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Swap/Asset/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Swap/CreditDefault/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Swap/Currency/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Swap/ForeignExchange/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Swap/Fpml/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Swap/InterestRate/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Token/Instrument.daml
- src/main/daml/Daml/Finance/Settlement/Batch.daml
- src/main/daml/Daml/Finance/Settlement/Instruction.daml
Changes from @akrmn to remove template-local let bindings
> Remove template-local let bindings

- daml.yaml
- src/main/daml/Daml/Finance/Claims/Lifecycle/Rule.daml
Relates to https://github.com/digital-asset/daml-finance/issues/1016
> Add tags for new dynamic instrument version

- CHANGELOG.md
- src/main/daml/Daml/Finance/Instrument/Option/Dividend/Election.daml
- src/main/daml/Daml/Finance/Interface/Instrument/Option/Dividend/Election/Factory.daml
Fixes https://github.com/digital-asset/daml-finance/issues/1040
> Removes the remove choice of the option dividend election factory

- package/test/daml/Daml.Finance.Instrument.Generic.Test/daml.yaml
- src/test/daml/Daml/Finance/Instrument/Generic/Test/ReverseConvertible.daml
Fixes https://github.com/digital-asset/daml-finance/issues/1046
> Implement FX Reverse Convertible using the generic instrument

- CHANGELOG.md
- src/main/daml/Daml/Finance/Account/Account.daml
- src/main/daml/Daml/Finance/Interface/Account/Account.daml
- src/main/daml/Daml/Finance/Interface/Account/Factory.daml
- src/test/daml/Daml/Finance/Account/Test/Account.daml
Solves https://github.com/digital-asset/daml-finance/issues/1036
> Removes remove from the account factory

- CHANGELOG.md
- docs/code-samples/getting-started/daml.yaml
- docs/code-samples/getting-started/daml.yaml.template
- docs/code-samples/lifecycling/daml.yaml
- docs/code-samples/lifecycling/daml.yaml.template
- docs/code-samples/lifecycling/daml/Scripts/CallableBond.daml
- docs/code-samples/lifecycling/daml/Scripts/FloatingRateBond.daml
- docs/code-samples/payoff-modeling/daml.yaml
- docs/code-samples/payoff-modeling/daml.yaml.template
- docs/code-samples/settlement/daml.yaml
- docs/code-samples/settlement/daml.yaml.template
Fixes https://github.com/digital-asset/daml-finance/issues/1060
> Fix lifecycling tutorial

- daml.yaml
- src/test/daml/Daml/Finance/Util/Test/Date/Calendar.daml
- src/test/daml/Daml/Finance/Util/Test/Date/DayCount.daml
- src/test/daml/Daml/Finance/Util/Test/Date/RollConvention.daml
- src/test/daml/Daml/Finance/Util/Test/Date/Schedule.daml
Required for https://github.com/digital-asset/docs.daml.com/pull/468
> Tests / code snippets for schedule tutorial

- src/main/daml/Daml/Finance/Account/Account.daml
- src/main/daml/Daml/Finance/Interface/Instrument/Types/FloatingRate.daml
> Avoid using `coerceContractId`

- CHANGELOG.md
- src/main/daml/Daml/Finance/Holding/Factory.daml
- src/main/daml/Daml/Finance/Interface/Holding/Factory.daml
- src/test/daml/Daml/Finance/Test/Util/HoldingDuplicates/Factory.daml
...to be consistent with the other keyed interfaces.
> Adding Remove and getKey to Holding Factory

- CHANGELOG.md
- package/main/daml/Daml.Finance.Data/daml.yaml
- package/main/daml/Daml.Finance.Instrument.Bond/daml.yaml
- package/main/daml/Daml.Finance.Instrument.Option/daml.yaml
- package/main/daml/Daml.Finance.Instrument.StructuredProduct/daml.yaml
- package/main/daml/Daml.Finance.Instrument.Swap/daml.yaml
- package/test/daml/Daml.Finance.Data.Test/daml.yaml
- package/test/daml/Daml.Finance.Instrument.Bond.Test/daml.yaml
- package/test/daml/Daml.Finance.Instrument.Equity.Test/daml.yaml
- package/test/daml/Daml.Finance.Instrument.Generic.Test/daml.yaml
- package/test/daml/Daml.Finance.Instrument.Option.Test/daml.yaml
- package/test/daml/Daml.Finance.Instrument.StructuredProduct.Test/daml.yaml
- package/test/daml/Daml.Finance.Instrument.Swap.Test/daml.yaml
- package/test/daml/Daml.Finance.Test.Util/daml.yaml
- src/main/daml/Daml/Finance/Data/Time/LedgerTime.daml
FIXES https://github.com/digital-asset/daml-finance/issues/836
> Remove key from LedgerTime

- CHANGELOG.md
- package/main/daml/Daml.Finance.Claims/daml.yaml
- package/main/daml/Daml.Finance.Instrument.Bond/daml.yaml
- package/main/daml/Daml.Finance.Instrument.Equity/daml.yaml
- package/main/daml/Daml.Finance.Instrument.Generic/daml.yaml
- package/main/daml/Daml.Finance.Instrument.Option/daml.yaml
- package/main/daml/Daml.Finance.Instrument.StructuredProduct/daml.yaml
- package/main/daml/Daml.Finance.Instrument.Swap/daml.yaml
- package/main/daml/Daml.Finance.Instrument.Token/daml.yaml
- package/main/daml/Daml.Finance.Interface.Claims/daml.yaml
- package/main/daml/Daml.Finance.Interface.Instrument.Base/daml.yaml
- package/main/daml/Daml.Finance.Interface.Instrument.Bond/daml.yaml
- package/main/daml/Daml.Finance.Interface.Instrument.Equity/daml.yaml
- package/main/daml/Daml.Finance.Interface.Instrument.Generic/daml.yaml
- package/main/daml/Daml.Finance.Interface.Instrument.Option/daml.yaml
- package/main/daml/Daml.Finance.Interface.Instrument.StructuredProduct/daml.yaml
- package/main/daml/Daml.Finance.Interface.Instrument.Swap/daml.yaml
- package/main/daml/Daml.Finance.Interface.Instrument.Token/daml.yaml
- package/main/daml/Daml.Finance.Lifecycle/daml.yaml
- package/test/daml/Daml.Finance.Instrument.Bond.Test/daml.yaml
- package/test/daml/Daml.Finance.Instrument.Equity.Test/daml.yaml
- package/test/daml/Daml.Finance.Instrument.Generic.Test/daml.yaml
- package/test/daml/Daml.Finance.Instrument.Option.Test/daml.yaml
- package/test/daml/Daml.Finance.Instrument.StructuredProduct.Test/daml.yaml
- package/test/daml/Daml.Finance.Instrument.Swap.Test/daml.yaml
- package/test/daml/Daml.Finance.Test.Util/daml.yaml
- src/main/daml/Daml/Finance/Interface/Instrument/Base/Instrument.daml
FIXES https://github.com/digital-asset/daml-finance/issues/1109
> Made the issuer a single-maintainer of the Instrument key

- CHANGELOG.md
- package/main/daml/Daml.Finance.Instrument.Generic/daml.yaml
- src/main/daml/Daml/Finance/Lifecycle/Rule/Distribution.daml
- src/main/daml/Daml/Finance/Lifecycle/Rule/Replacement.daml
FIXES https://github.com/digital-asset/daml-finance/issues/1111
> Replace lookupByKey in Distribution and Replacement

- docs/code-samples/getting-started/daml/Scripts/Lifecycling.daml
- docs/code-samples/getting-started/daml/Scripts/Settlement.daml
- docs/code-samples/getting-started/daml/Scripts/Transfer.daml
- docs/code-samples/getting-started/daml/Workflow/CreateAccount.daml
- docs/code-samples/getting-started/daml/Workflow/CreditAccount.daml
- docs/code-samples/getting-started/daml/Workflow/DvP.daml
- docs/code-samples/getting-started/daml/Workflow/Transfer.daml
- docs/code-samples/lifecycling/daml/Scripts/CallableBond.daml
- docs/code-samples/lifecycling/daml/Scripts/FloatingRateBond.daml
- docs/code-samples/lifecycling/daml/Workflow/CreateAccount.daml
- docs/code-samples/lifecycling/daml/Workflow/CreditAccount.daml
- docs/code-samples/payoff-modeling/daml/PayoffBuilder.daml
- docs/code-samples/payoff-modeling/daml/Util/Lifecycle.daml
- docs/code-samples/payoff-modeling/daml/Util/Setup.daml
- docs/code-samples/settlement/daml/Scripts/Internal.daml
- docs/code-samples/settlement/daml/Scripts/Transfer.daml
- docs/code-samples/settlement/daml/Workflow/CreateAccount.daml
- docs/code-samples/settlement/daml/Workflow/CreditAccount.daml
FIXES https://github.com/digital-asset/daml-finance/issues/1106
> minor amendments to the getting started and tutorials

- daml.yaml
- src/main/daml/Daml/Finance/Interface/Types/Common/Types.daml
FIXES https://github.com/digital-asset/daml-finance/issues/1097
> fix pixel art for docs

- src/main/daml/Daml/Finance/Instrument/Swap/Asset/DistributionRule.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/Asset.daml
Fixes https://github.com/digital-asset/daml-finance/issues/1145
> Multiple div events for asset swaps

- src/test/daml/Daml/Finance/Instrument/Bond/Test/FixedRate.daml
- src/test/daml/Daml/Finance/Instrument/Bond/Test/FloatingRate.daml
- src/test/daml/Daml/Finance/Instrument/Bond/Test/InflationLinked.daml
- src/test/daml/Daml/Finance/Instrument/Bond/Test/ZeroCoupon.daml
- src/test/daml/Daml/Finance/Instrument/StructuredProduct/Test/BarrierReverseConvertible.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/Asset.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/CreditDefault.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/Currency.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/ForeignExchange.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/Fpml.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/InterestRate.daml
Fixes https://github.com/digital-asset/daml-finance/issues/1153
> Unify test variable names

- shell.nix
Sorry for the cumbersome process around this.
> bump daml hashes

- src/main/daml/Daml/Finance/Settlement/HTLC.daml
- src/test/daml/Daml/Finance/Settlement/Test/TransferWithHTLC.daml
- Added `cashSender` and `cashReceiver` as parties
- Tested failure scenario
> improve example

- README.md
> Correct build command in README.md

- src/main/daml/Daml/Finance/Instrument/Swap/Fpml/Util.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/Fpml.daml
Fixes https://github.com/digital-asset/daml-finance/issues/1209
> round up/down/nearest incl tests for negative numbers

- CHANGELOG.md
- package/main/daml/Daml.Finance.Claims/daml.yaml
- package/main/daml/Daml.Finance.Data/daml.yaml
- package/main/daml/Daml.Finance.Instrument.Equity/daml.yaml
- package/main/daml/Daml.Finance.Instrument.Generic/daml.yaml
- package/main/daml/Daml.Finance.Instrument.Option/daml.yaml
- package/main/daml/Daml.Finance.Instrument.StructuredProduct/daml.yaml
- package/main/daml/Daml.Finance.Instrument.Swap/daml.yaml
- package/main/daml/Daml.Finance.Interface.Data/daml.yaml
- package/main/daml/Daml.Finance.Interface.Instrument.Equity/daml.yaml
- package/main/daml/Daml.Finance.Interface.Instrument.Option/daml.yaml
- package/main/daml/Daml.Finance.Interface.Lifecycle/daml.yaml
- package/main/daml/Daml.Finance.Lifecycle/daml.yaml
- package/test/daml/Daml.Finance.Data.Test/daml.yaml
- package/test/daml/Daml.Finance.Instrument.Equity.Test/daml.yaml
- package/test/daml/Daml.Finance.Instrument.Generic.Test/daml.yaml
- package/test/daml/Daml.Finance.Instrument.Option.Test/daml.yaml
- package/test/daml/Daml.Finance.Instrument.Swap.Test/daml.yaml
- package/test/daml/Daml.Finance.Test.Util/daml.yaml
- src/main/daml/Daml/Finance/Interface/Lifecycle/Effect.daml
As discussed in https://discuss.daml.com/t/interface-effect-why-the-provider-has-visibility-on-all-sub-transactions-triggered-by-claim-ing-an-effect/7154/2
> remove incorrect statement from doc

- docs/code-samples/README.md
Fixes https://github.com/digital-asset/daml-finance/issues/1220
> Update links to the Daml repo

- scripts/test-sdk-daml-finance-templates.sh
- scripts/utility/install-sdk.sh
Fixes https://github.com/digital-asset/daml-finance/issues/1227
> Fix the quickstarter testing script

- CHANGELOG.md
- src/main/daml/Daml/Finance/Holding/Factory.daml
- src/test/daml/Daml/Finance/Holding/Test/Holding.daml
fixes https://github.com/digital-asset/daml-finance/issues/1231
> Fix holding factory reference observers
