- .gitignore
- Makefile
- src/main/daml/Daml/Finance/Common/Date/DayCount.daml
- src/main/daml/Daml/Finance/Interface/Asset/Account.daml
- src/main/daml/Daml/Finance/Interface/Asset/Factory/Account.daml
- src/main/daml/Daml/Finance/Interface/Asset/Factory/Holding.daml
- src/main/daml/Daml/Finance/Interface/Asset/Fungible.daml
- src/main/daml/Daml/Finance/Interface/Asset/Holding.daml
- src/main/daml/Daml/Finance/Interface/Asset/Instrument.daml
- src/main/daml/Daml/Finance/Interface/Asset/Lockable.daml
- src/main/daml/Daml/Finance/Interface/Common/Disclosure.daml
- src/main/daml/Daml/Finance/Interface/Common/Util.daml
This is not yet included in the Ci, but I wanted to try how it looks like. 
Changes:
- hide some functions involving account and instrument references
- add comment to type synonyms (if you agree this makes sense I will do it across the library, otherwise will remove it)
- removed one unused function
There are a couple of quirks when generating doc for interfaces, which we should raise:
- interface methods don't seem to be displayed nicely (**bold** is not taken into account)
- interface methods are also duplicated as functions
- Plenty of extra type-classes are displayed (and the fact that we use `I` for all interfaces makes things confusing)
It is an open point where this docs should be hosted and how it gets integrated with the SDK doc. What currently happens is the following:
- doc …
> Add `make` option to generate automated doc, some polishing

- src/main/daml/Daml/Finance/Interface/Settlement/Instructable.daml
- src/main/daml/Daml/Finance/Lifecycle/SettlementRule.daml
- src/main/daml/Daml/Finance/Settlement/Batch.daml
- src/test/daml/Daml/Finance/Bond/Test/Util.daml
- src/test/daml/Daml/Finance/Bond/Test/ZeroCoupon.daml
- src/test/daml/Daml/Finance/Derivative/Test/CallableBond.daml
- src/test/daml/Daml/Finance/Derivative/Test/EuropeanOption.daml
- src/test/daml/Daml/Finance/Derivative/Test/ForwardCash.daml
- src/test/daml/Daml/Finance/Derivative/Test/ForwardPhysical.daml
- src/test/daml/Daml/Finance/Derivative/Test/Intermediated/BondCoupon.daml
- src/test/daml/Daml/Finance/Equity/Test/CashDividend.daml
- src/test/daml/Daml/Finance/Equity/Test/CashTakeover.daml
- src/test/daml/Daml/Finance/Equity/Test/Merger.daml
- src/test/daml/Daml/Finance/Equity/Test/ShareDividend.daml
- src/test/daml/Daml/Finance/Equity/Test/ShareTakeover.daml
- src/test/daml/Daml/Finance/Settlement/Test/Batch.daml
- src/test/daml/Daml/Finance/Settlement/Test/BatchWithRoute.daml
- src/test/daml/Daml/Finance/Settlement/Test/Intermediated.daml
- src/test/daml/Daml/Finance/Settlement/Test/Transfer.daml
Also
- rename requestors to provider
- change from Parties to Party
Motivation:
- we want to have as few Batch Factories as possible, given that this contract needs to be created directly at ledger initialisation (unless we want to introduce a factory's factory). Adding observers + flexible controllers allows us to use a public party mechanism, which reduces the number of contracts that we need.
- This came out while trying to port some CBDC sandbox code to the new library
The flexible controllers are now signatories of the batch + instructions. 
The previous scenario can be reproduced with the new version (by setting observers = empty).
I will need to think a bit better how this works in the case of `BatchFactoryWithIntermediaries` as we generally do not want to give a public party …
> Add observers to `Instructable`, introduce flexible controller

- Makefile
- src/main/daml/Daml/Finance/Asset/NonTransferable.daml
- src/main/daml/Daml/Finance/Common/Date/Calendar.daml
- src/main/daml/Daml/Finance/Derivative/Election.daml
- src/main/daml/Daml/Finance/Derivative/Instrument.daml
- src/main/daml/Daml/Finance/Interface/Asset/Types.daml
- src/main/daml/Daml/Finance/Interface/Derivative/Util/Claims.daml
- src/main/daml/Daml/Finance/Interface/Lifecycle/Effect.daml
- src/main/daml/Daml/Finance/Interface/Lifecycle/SettlementRule.daml
- src/main/daml/Daml/Finance/Interface/Settlement/Instructable.daml
- src/main/daml/Daml/Finance/Interface/Settlement/Settleable.daml
- src/main/daml/Daml/Finance/Lifecycle/SettlementRule.daml
- src/main/daml/Daml/Finance/Settlement/Batch.daml
This is related to point 1 in https://github.com/DACH-NY/daml-finance/issues/269.
Additionally, add `make` option to generate documentation in json format
> Fix character escaping in docs

- src/main/daml/Daml/Finance/Asset/Fungible.daml
- src/main/daml/Daml/Finance/Asset/NonFungible.daml
- src/test/daml/Daml/Finance/Asset/Test/Common.daml
- src/test/daml/Daml/Finance/Asset/Test/Fungible.daml
- src/test/daml/Daml/Finance/Asset/Test/NoCrossTransfer.daml
- src/test/daml/Daml/Finance/Asset/Test/NonFungible.daml
- src/test/daml/Daml/Finance/Bond/Test/Util.daml
- src/test/daml/Daml/Finance/Bond/Test/ZeroCoupon.daml
- src/test/daml/Daml/Finance/Derivative/Test/CallableBond.daml
- src/test/daml/Daml/Finance/Derivative/Test/EuropeanOption.daml
- src/test/daml/Daml/Finance/Derivative/Test/ForwardCash.daml
- src/test/daml/Daml/Finance/Derivative/Test/ForwardPhysical.daml
- src/test/daml/Daml/Finance/Derivative/Test/Intermediated/BondCoupon.daml
- src/test/daml/Daml/Finance/Equity/Test/CashDividend.daml
- src/test/daml/Daml/Finance/Equity/Test/CashTakeover.daml
- src/test/daml/Daml/Finance/Equity/Test/Merger.daml
- src/test/daml/Daml/Finance/Equity/Test/ShareDividend.daml
- src/test/daml/Daml/Finance/Equity/Test/ShareTakeover.daml
- src/test/daml/Daml/Finance/Settlement/Test/BatchWithRoute.daml
- src/test/daml/Daml/Finance/Settlement/Test/Intermediated.daml
- src/test/daml/Daml/Finance/Settlement/Test/Transfer.daml
Addresses https://github.com/DACH-NY/daml-finance/issues/262
This forces holdings allocated to a specific account to have the same type.
It relies on a public party mechanism to disclose the holding factory.
Open questions:
- we need one holding factory per custodian, so maybe it makes sense to introduce a `HoldingFactoryFactory`
- upgrade scenario for holdings does look a bit more complex now
- are we happy with the public party disclosure mechanism?
- given that we are coupling accounts and holdings, should we introduce 1 account implementation per holding type instead of relying on holding factories?
Upgrade scenario for holdings:
- introduce V2 holding
- for each V1 holding factory, introduce V2 holding Factory
- for each account referencing the V1 factory, create new account …
> Make transfer use Credit

- src/main/daml/Daml/Finance/Interface/Asset/Types.daml
- src/main/daml/Daml/Finance/Lifecycle/SettlementRule.daml
Adresses https://github.com/DACH-NY/daml-finance/issues/187
It's not actually the effect id that needs to be unique. Rather we need to generate a unique batch id for settlement in the lifecycle rule, so that instruction ids don't clash when claiming multiple times for different owners.
The stop-gap solution for now is to hash the effect id together with the custodian and the owner. This still breaks down if for some reason one would split a holding and claim each of the resulting ones separately, or if one claims holdings on the same instruments from different accounts.
A proper solution would probably be to take a random id from external, see https://github.com/DACH-NY/daml-finance/issues/283 .
> Fix batch id generation in lifecycle settlement rule

- package/main/daml/Daml.Finance.Bond/daml.yaml
- package/main/daml/Daml.Finance.Interface.Bond/README.md
- package/main/daml/Daml.Finance.Interface.Bond/daml.yaml
- package/main/daml/Daml.Finance.Interface.Bond/daml/Daml/Finance/Interface/Bond
- scripts/build.sh
- scripts/clean.sh
- src/main/daml/Daml/Finance/Asset/Instrument.daml
- src/main/daml/Daml/Finance/Bond/FixedRate.daml
- src/main/daml/Daml/Finance/Bond/FloatingRate.daml
- src/main/daml/Daml/Finance/Bond/InflationLinked.daml
- src/main/daml/Daml/Finance/Bond/ZeroCoupon.daml
- src/main/daml/Daml/Finance/Derivative/Factory.daml
- src/main/daml/Daml/Finance/Equity/Factory.daml
- src/main/daml/Daml/Finance/Interface/Asset/Factory/Instrument.daml
- src/main/daml/Daml/Finance/Interface/Bond/FixedRate.daml
- src/main/daml/Daml/Finance/Interface/Bond/FloatingRate.daml
- src/main/daml/Daml/Finance/Interface/Bond/InflationLinked.daml
- src/main/daml/Daml/Finance/Interface/Bond/ZeroCoupon.daml
- src/main/daml/Daml/Finance/Interface/Derivative/Factory.daml
- src/main/daml/Daml/Finance/Interface/Equity/Factory.daml
- src/test/daml/Daml/Finance/Bond/Test/Util.daml
- src/test/daml/Daml/Finance/Bond/Test/ZeroCoupon.daml
This introduced a dependency from `D.F.Interface.Bond` to `D.F.Common`, which is undesirable as the Common package contains utility function implementations. https://github.com/DACH-NY/daml-finance/issues/288 is to address this.
I haven't included the factories in the tests, as I wanted to do https://github.com/DACH-NY/daml-finance/issues/280 first, which should simplify a lot of parameter passing around.
> Add instrument factories

- src/main/daml/Daml/Finance/Instrument/Bond/FixedRate.daml
- src/main/daml/Daml/Finance/Instrument/Bond/FloatingRate.daml
- src/main/daml/Daml/Finance/Instrument/Bond/InflationLinked.daml
- src/main/daml/Daml/Finance/Instrument/Bond/Util.daml
- src/main/daml/Daml/Finance/Interface/Instrument/Bond/FixedRate.daml
- src/main/daml/Daml/Finance/Interface/Instrument/Bond/FloatingRate.daml
- src/main/daml/Daml/Finance/Interface/Instrument/Bond/InflationLinked.daml
- src/test/daml/Daml/Finance/Instrument/Bond/Test/Util.daml
I have included PeriodicSchedule in the bond definitions. This enables the full functionality of the PeriodicSchedule (including end stubs and EOM roll conventions) in the bond templates.
Next, I will update the bond tutorial / documentation. I will submit that as a separate PR, to reduce the risk of merge conflicts.
> Include PeriodicSchedule in bonds

- docs/README.md
- docs/source/getting-started/download-daml-finance.rst
- docs/source/getting-started/intro.rst
- docs/source/getting-started/lifecycling.rst
- docs/source/index.rst
- docs/source/tutorial/bond-extension.rst
- docs/source/tutorial/contingent-claims-instrument.rst
- docs/source/tutorial/derivative-extension.rst
- docs/source/tutorial/intro.rst
- src/test/daml/Daml/Finance/Instrument/Bond/Test/Util.daml
I have updated the bond tutorial to describe how to use a PeriodicSchedule, which is now required after the latest change to the bond templates. 
I also did some minor changes to the overall docs, including renaming `Install Daml Finance` to `Download Daml Finance` as per feedback from @GeorgSchneider previously. I updated README.md as well, to describe how to install the doc generation locally.
> Update the bond tutorial to reflect PeriodicSchedule

- src/main/daml/Daml/Finance/Instrument/Generic/Election.daml
- src/test/daml/Daml/Finance/Instrument/Generic/Test/CallableBond.daml
- src/test/daml/Daml/Finance/Instrument/Generic/Test/EuropeanOption.daml
Remove the requirement for the `elector` to provide an Id when requesting to create a new election.
> Election Identifier

- src/main/daml/Daml/Finance/Interface/Holding/Factory/Account.daml
- src/main/daml/Daml/Finance/Interface/Settlement/Factory.daml
Seems that `make doc-html` breaks if the comments after template variables are not "properly" indented. I have fixed a couple of those problems below. Doc building now works again, at least on my machine.
> Fix comments that broke doc building

- src/main/daml/Daml/Finance/Interface/Types/Date/DayCount.daml
- src/main/daml/Daml/Finance/Util/Date/DayCount.daml
- src/test/daml/Daml/Finance/Util/Test/Date/DayCount.daml
I have aligned the Daml Finance day-count enums with the ones in ISDA CDM and ISO20022. Since neither of those two standards is complete, we decided to stick with the current Daml Finance enums and map to both standards in the comments.
Also, there were two day-count methods that existed in both ISDA CDM and ISO20022 but not in Daml Finance. I have now implemented these as well:
- ActAct_AFB: implemented according to the 1999 ISDA paper (including the tests provided there)
- Act365L: implemented according to the 2006 ISDA definitions
> Align day-count enums with ISDA CDM and ISO20022

- docs/source/packages/instrument-extensions.rst
- docs/source/tutorials/instrument-modeling/contingent-claims-instrument.rst
- package/main/daml/Daml.Finance.Instrument.Bond/daml.yaml
- package/test/daml/Daml.Finance.Instrument.Bond.Test/daml.yaml
I have created package documentation for the new Swap package. 
I also updated the Bond documentation references after the utility functions (shared between Swap and Bond) were moved to a different package.
> Write package documentation for Swaps

- src/main/daml/Daml/Finance/Instrument/Generic/Util.daml
- src/main/daml/Daml/Finance/Instrument/Swap/ForeignExchange.daml
- src/main/daml/Daml/Finance/Interface/Instrument/Swap/ForeignExchange.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/ForeignExchange.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/Util.daml
I have implemented a first version of foreign exchange swaps. This is a fairly simple kind of swap, consisting of only two FX transactions (i.e. no periodic interest rate payments), so I could get rid of the PeriodicSchedule structure.
There are a few potential improvements to the contingent claims utility functions for swaps/bonds that I plan to implement as part of a separate PR. They are tracked in this issue for now: https://github.com/digital-asset/daml-finance/issues/149
Regarding documentation: I plan to add a swaps tutorial once we have a few more payoffs.
> Implement FX Swaps

- src/main/daml/Daml/Finance/Instrument/Bond/FixedRate.daml
- src/main/daml/Daml/Finance/Instrument/Bond/FloatingRate.daml
- src/main/daml/Daml/Finance/Instrument/Bond/InflationLinked.daml
- src/main/daml/Daml/Finance/Instrument/Bond/ZeroCoupon.daml
- src/main/daml/Daml/Finance/Instrument/Generic/Util.daml
- src/main/daml/Daml/Finance/Instrument/Swap/CreditDefault.daml
- src/main/daml/Daml/Finance/Instrument/Swap/Currency.daml
- src/main/daml/Daml/Finance/Instrument/Swap/ForeignExchange.daml
- src/main/daml/Daml/Finance/Instrument/Swap/InterestRate.daml
- src/main/daml/Daml/Finance/Interface/Instrument/Swap/CreditDefault.daml
- src/test/daml/Daml/Finance/Instrument/Bond/Test/ZeroCoupon.daml
- src/test/daml/Daml/Finance/Instrument/Equity/Test/Dividend.daml
- src/test/daml/Daml/Finance/Instrument/Generic/Test/CallableBond.daml
- src/test/daml/Daml/Finance/Instrument/Generic/Test/EuropeanOption.daml
- src/test/daml/Daml/Finance/Instrument/Generic/Test/ForwardCash.daml
- src/test/daml/Daml/Finance/Instrument/Generic/Test/ForwardPhysical.daml
- src/test/daml/Daml/Finance/Instrument/Generic/Test/Intermediated/BondCoupon.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/CreditDefault.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/Util.daml
- src/test/daml/Daml/Finance/Settlement/Test/Batch.daml
- src/test/daml/Daml/Finance/Settlement/Test/BatchWithIntermediaries.daml
- src/test/daml/Daml/Finance/Settlement/Test/Intermediated.daml
- src/test/daml/Daml/Finance/Settlement/Test/Transfer.daml
I have created a first version of credit default swaps: https://github.com/digital-asset/daml-finance/issues/143
This uses the `until` node in contingent claims. I noticed that this is not currently pruned automatically in the lifecycle code. I have tracked here: https://github.com/digital-asset/daml-finance/issues/166
I would like to discuss that when Matteo is back and solve any follow-up work as part of a separate PR.
In order to more easily evaluate different scenarios, I implemented two different test cases:
1. a CDS which has a credit event during the lifetime
2. a CDS which does not have a credit event during the lifetime
I added two utility functions for creating the claims. I also found an extra possibility for improvement, tracked here: …
> Implement credit default swaps

- docs/source/tutorials/getting-started/intro.rst
In order to make it clear that the Daml Finance quick start does not automatically install the Demo App, I have broken up the Getting Started page in two sections.
> Separate demo app from daml finance in getting started

- src/main/daml/Daml/Finance/Instrument/Bond/FixedRate/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Bond/FloatingRate/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Bond/ZeroCoupon/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Generic/Util.daml
- src/main/daml/Daml/Finance/Instrument/Swap/Asset/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Swap/CreditDefault/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Swap/Currency/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Swap/ForeignExchange/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Swap/Fpml/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Swap/Fpml/Util.daml
- src/main/daml/Daml/Finance/Instrument/Swap/InterestRate/Instrument.daml
- src/main/daml/Daml/Finance/Interface/Types/Fpml.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/Fpml.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/Util.daml
I have added support for specifying notional in each swapStream, which is required for the sample trade as specified in the **notional / holding**  section here: https://github.com/digital-asset/daml-finance/issues/226 
For consistency, I implemented support for notional in all CC utility functions, even though it is not currently used in the other Swap/Bond templates (could potentially change in the future).
> Add support for FpML swapStream notional

- src/test/daml/Daml/Finance/Instrument/Bond/Test/FixedRate.daml
- src/test/daml/Daml/Finance/Instrument/Bond/Test/FloatingRate.daml
- src/test/daml/Daml/Finance/Instrument/Bond/Test/InflationLinked.daml
- src/test/daml/Daml/Finance/Instrument/Bond/Test/Util.daml
- src/test/daml/Daml/Finance/Instrument/Bond/Test/ZeroCoupon.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/Asset.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/CreditDefault.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/Currency.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/ForeignExchange.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/Fpml.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/InterestRate.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/Util.daml
@markus-da during the implementation of my previous PR, I noticed that the bond and swap tests are now using a few redundant parties. This is an attempt at a cleanup, let me know what you think.
I also noticed that in the bond tests we have two parties, namely `depository` and `custodian`, which are respectively depositories of the cash and bond instrument. In the swap tests, the `custodian` plays both roles. Shall we align?
> Cleanup bond and swap tests

- src/main/daml/Daml/Finance/Lifecycle/Rule/Claim.daml
Now that we the instrument holding is not upgraded immediately, we no longer need the `owner` and `custodian` as signatories of the `Claim` rule.
> Remove unnecessary signatory constraints

- package/main/daml/Daml.Finance.Settlement/daml.yaml
- package/test/daml/Daml.Finance.Instrument.Equity.Test/daml.yaml
- package/test/daml/Daml.Finance.Instrument.Generic.Test/daml.yaml
- package/test/daml/Daml.Finance.Settlement.Test/daml.yaml
- src/main/daml/Daml/Finance/Settlement/Factory.daml
- src/main/daml/Daml/Finance/Settlement/Hierarchy.daml
- src/test/daml/Daml/Finance/Instrument/Generic/Test/Intermediated/BondCoupon.daml
- src/test/daml/Daml/Finance/Settlement/Test/BatchWithIntermediaries.daml
If you want to avoid the refactoring noise, feel free to review only the last commit. 
I had added a second script to the `BondCoupon` test where a coupon on a bond is paid across an account hierarchy.
The settlement of the cash leg follows a different hierarchy than the settlement of the security leg.
This is part of https://github.com/digital-asset/daml-finance/issues/282.
We use all of the settlement tricks recently added by @johan-da: DebitSender, CreditReceiver, PassThrough
> Rework `FactoryWithIntermediaries`, add example of atomic effect settlement across an account hierarchy

- daml.yaml
- package/main/daml/ContingentClaims.Core/daml.yaml
- package/main/daml/ContingentClaims.Lifecycle/daml.yaml
- package/main/daml/ContingentClaims.Valuation/daml.yaml
- package/main/daml/Daml.Finance.Claims/daml.yaml
- package/main/daml/Daml.Finance.Instrument.Bond/daml.yaml
- package/main/daml/Daml.Finance.Instrument.Generic/daml.yaml
- package/main/daml/Daml.Finance.Instrument.Swap/daml.yaml
- package/main/daml/Daml.Finance.Interface.Claims/daml.yaml
- package/main/daml/Daml.Finance.Interface.Instrument.Generic/daml.yaml
- package/test/daml/ContingentClaims.Test/daml.yaml
- package/test/daml/Daml.Finance.Instrument.Bond.Test/daml.yaml
- package/test/daml/Daml.Finance.Instrument.Generic.Test/daml.yaml
I have updated the daml-ctl version to make sure `build-options` are aligned (target=1.15), since this is required for java codegen.
> New daml ctl version

- src/main/daml/Daml/Finance/Settlement/Hierarchy.daml
- src/test/daml/Daml/Finance/Settlement/Test/Hierarchy.daml
This fixes a bug in the current implementation.
Assume that we have chains [A -> B -> C] and [ D -> B -> C ] and want to find a path to root custodian.
Previously `locateParty` would throw an error. Now it returns the path [ B -> C ]
> Fix bug in `Hierarchy.locateParty`

- docs/source/concepts/asset-model.rst
- docs/source/tutorials/instrument-modeling/swap-extension.rst
- src/test/daml/Daml/Finance/Instrument/Swap/Test/ForeignExchange.daml
- Link to other parts of the documentation: the asset model (OTC Swap), account.credit, SwapStream data type
- Specify functionality supported in interest rate / currency swap vs FpML swap
- Improve some explanations
> Improve tutorial: How To Use the Swap Extension Package

- src/main/daml/Daml/Finance/Claims/Lifecycle/Rule.daml
- src/main/daml/Daml/Finance/Instrument/Generic/Lifecycle/Rule.daml
- src/main/daml/Daml/Finance/Interface/Lifecycle/Rule/Lifecycle.daml
- src/main/daml/Daml/Finance/Lifecycle/Rule/Distribution.daml
- src/main/daml/Daml/Finance/Lifecycle/Rule/Replacement.daml
- src/test/daml/Daml/Finance/Instrument/Bond/Test/Util.daml
- src/test/daml/Daml/Finance/Instrument/Equity/Test/Dividend.daml
- src/test/daml/Daml/Finance/Instrument/Equity/Test/Merger.daml
- src/test/daml/Daml/Finance/Instrument/Equity/Test/StockSplit.daml
- src/test/daml/Daml/Finance/Instrument/Generic/Test/CallableBond.daml
- src/test/daml/Daml/Finance/Instrument/Generic/Test/EuropeanOption.daml
- src/test/daml/Daml/Finance/Instrument/Generic/Test/ForwardCash.daml
- src/test/daml/Daml/Finance/Instrument/Generic/Test/ForwardPhysical.daml
- src/test/daml/Daml/Finance/Instrument/Generic/Test/Intermediated/BondCoupon.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/Util.daml
This allows client applications to disambiguate when handling multiple instruments
> Add id and description to `Lifecycle` interface

- docs/code-samples/getting-started/daml/Scripts/Lifecycling.daml
- src/main/daml/Daml/Finance/Claims/Lifecycle/Rule.daml
- src/main/daml/Daml/Finance/Instrument/Equity/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Generic/Lifecycle/Rule.daml
- src/main/daml/Daml/Finance/Interface/Instrument/Equity/Instrument.daml
- src/main/daml/Daml/Finance/Interface/Lifecycle/Effect.daml
- src/main/daml/Daml/Finance/Interface/Lifecycle/Event/Distribution.daml
- src/main/daml/Daml/Finance/Interface/Lifecycle/Event/Replacement.daml
- src/main/daml/Daml/Finance/Lifecycle/Effect.daml
- src/main/daml/Daml/Finance/Lifecycle/ElectionEffect.daml
- src/main/daml/Daml/Finance/Lifecycle/Event/Distribution.daml
- src/main/daml/Daml/Finance/Lifecycle/Event/Replacement.daml
- src/main/daml/Daml/Finance/Lifecycle/Rule/Claim.daml
- src/main/daml/Daml/Finance/Lifecycle/Rule/Distribution.daml
- src/main/daml/Daml/Finance/Lifecycle/Rule/Replacement.daml
- src/test/daml/Daml/Finance/Instrument/Equity/Test/Dividend.daml
- src/test/daml/Daml/Finance/Instrument/Equity/Test/Merger.daml
- src/test/daml/Daml/Finance/Instrument/Equity/Test/StockSplit.daml
This brings the effect in line with settlement by using `Optional Time` instead of `Date`.
It also removes a bunch of Date -> Time conversions.
All our lifecycle events are settled "immediately" (the `settlementTime` coincides with the time of the event).
> Use time on effects instead of Date

- package/main/daml/Daml.Finance.Interface.Data/daml.yaml
- package/test/daml/Daml.Finance.Data.Test/daml.yaml
- src/main/daml/Daml/Finance/Claims/Util/Builders.daml
- src/main/daml/Daml/Finance/Data/Reference/HolidayCalendar.daml
- src/main/daml/Daml/Finance/Interface/Data/Reference/HolidayCalendar.daml
- src/main/daml/Daml/Finance/Interface/Data/Reference/HolidayCalendar/Factory.daml
- src/main/daml/Daml/Finance/Interface/Data/TimeObservable.daml
- src/main/daml/Daml/Finance/Interface/Holding/Factory.daml
- src/test/daml/Daml/Finance/Data/Test/HolidayCalendar.daml
- src/test/daml/Daml/Finance/Instrument/Bond/Test/FixedRate.daml
- src/test/daml/Daml/Finance/Instrument/Bond/Test/FloatingRate.daml
- src/test/daml/Daml/Finance/Instrument/Bond/Test/InflationLinked.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/Asset.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/CreditDefault.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/Currency.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/Fpml.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/InterestRate.daml
- align terminology (agency -> provider)
- remove redundant identifier
- add interface and factory
The interface and factory feel a bit boiler-platy, given that most business logic already uses the common data type `HolidayCalendarData`. However it is required if we want to stick to the "Factory" pattern
> Calendar improvements

- src/main/daml/Daml/Finance/Holding/Util.daml
- src/main/daml/Daml/Finance/Interface/Settlement/Batch.daml
- src/main/daml/Daml/Finance/Interface/Settlement/Instruction.daml
- src/main/daml/Daml/Finance/Interface/Util/Disclosure.daml
- src/main/daml/Daml/Finance/Settlement/Batch.daml
- src/main/daml/Daml/Finance/Settlement/Instruction.daml
- src/test/daml/Daml/Finance/Settlement/Test/Batch.daml
1. **Restriction for settling individual `Instruction`** 
To avoid instructions being settled individually, i.e., not as part of the batch, we require the `requestors` and at least on of the `settlers` to settle `Instruction`s. Any of the `settlers` can still trigger a settlement of the `Batch` (and as a consequence its `Instruction`s).
2. **`requestors` can now cancel a `Batch` (and its `Instruction`s)** 
3. **Changed the authorization for `RemoveObservers`**
For disclosure purposes, I had to change the authorization for `RemoveObservers`. Now any of the parties of a context can remove the whole context (and clean up for the others). 
These changes do not affect the quickstarter 
**follow up:** I think we should factor out the actual choice bodies of the `Disclosure.I` (as we have done …
> Cancel of settlement

- package/main/daml/ContingentClaims.Lifecycle/daml.yaml
- package/main/daml/Daml.Finance.Claims/daml.yaml
- package/test/daml/ContingentClaims.Test/daml.yaml
- src/main/daml/ContingentClaims/Lifecycle/Lifecycle.daml
- src/test/daml/ContingentClaims/Test/Lifecycle.daml
Fixes https://github.com/digital-asset/contingent-claims/issues/86 and https://github.com/digital-asset/contingent-claims/issues/73.
This change ensures that a failed `exercise` will result in an unchanged claim. This has the benefit that it is very easy to check if an election has failed by checking `input == output`
On the other hand, it means that often we will need to apply a `lifecycle` immediately after an `exercise`. This is already the default behaviour in `Daml.Finance.Claims`, but could potentially also be made the default behaviour on the contingent claims layer.
Happy to hear your thoughts
> contingent claims: make failed elections non-effectful

- package/main/daml/Daml.Finance.Claims/daml.yaml
- package/main/daml/Daml.Finance.Instrument.Bond/daml.yaml
- package/main/daml/Daml.Finance.Instrument.Swap/daml.yaml
- src/main/daml/Daml/Finance/Claims/Util.daml
- src/main/daml/Daml/Finance/Claims/Util/Builders.daml
- src/main/daml/Daml/Finance/Instrument/Bond/FixedRate/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Bond/FloatingRate/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Bond/InflationLinked/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Bond/Util.daml
- src/main/daml/Daml/Finance/Instrument/Bond/ZeroCoupon/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Swap/Asset/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Swap/CreditDefault/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Swap/Currency/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Swap/ForeignExchange/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Swap/Fpml/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Swap/Fpml/Util.daml
- src/main/daml/Daml/Finance/Instrument/Swap/InterestRate/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Swap/Util.daml
- src/test/daml/Daml/Finance/Instrument/Bond/Test/FloatingRate.daml
- src/test/daml/Daml/Finance/Instrument/Bond/Test/InflationLinked.daml
- src/test/daml/Daml/Finance/Instrument/Generic/Test/Util.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/Asset.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/CreditDefault.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/Fpml.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/InterestRate.daml
- src/test/daml/Daml/Finance/Test/Util/Time.daml
Fixes https://github.com/digital-asset/daml-finance/issues/386
This PR removes the dependency of Daml.Finance.Claims on Daml.Finance.Data.
By so doing, it makes Daml.Finance.Claims agnostic to the specific
- calendar implementation
- logic to convert `Date` to `Time`
where we have made a specific choice, but a user could want to make a different one.
As a next step, I would like to take `prepareAndTagClaims` out of the builder functions, to simplify their signature and make them return pure `Claim` objects.  However, I won't feel to bad if I don't manage before the release.
> Decouple D.F.Claims from D.F.Data

- package/main/daml/Daml.Finance.Instrument.Swap/daml.yaml
- package/main/daml/Daml.Finance.Interface.Instrument.Swap/daml.yaml
- package/test/daml/Daml.Finance.Instrument.Swap.Test/daml.yaml
- src/main/daml/Daml/Finance/Instrument/Swap/Fpml/Util.daml
- src/main/daml/Daml/Finance/Interface/Instrument/Swap/Fpml/FpmlTypes.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/Fpml.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/Util.daml
Implement selected, official FpML IRS examples as test cases, the first 3 of these:
https://www.fpml.org/spec/fpml-5-11-7-rec-1/html/confirmation/fpml-5-11-examples.html#s2
- Example 1 - Fixed/Floating Single Currency Interest Rate Swap
- Example 2 - Fixed/Floating Single Currency Interest Rate Swap with Initial Stub Period and Notional Amortization
- Example 3 - Fixed/Floating Single Currency Interest Rate Swap with Compounding, Payment Delay and Final Rate Rounding
Turns out four new features are needed to cover these properly. I have opened separate issues for that. In order to make this easier to review, I have so far implemented these sample trades using currently supported configurations and added links to issues in the Test. I plan to cover those one PR at a time.
> Add three additional Fpml swap sample trades

- src/main/daml/Daml/Finance/Instrument/Swap/Fpml/Util.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/Fpml.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/Util.daml
I used to drive the floating interest rate calculation from the calculationSchedule (and treat each calculation period independently, relying on claims netting). With interest compounding I had to drive the calculation from the paymentSchedule, in order to combine the calculation periods as specified in the FpML. 
This was quite a significant change, so I have only implemented one compounding method in this PR. Once merged, I plan to implement the others and then merge the calculations into one single function, `calculateFloatingPaymentClaimsFromSwapStream`.
> Implement straight compounding of interest for FpML swaps

- src/main/daml/Daml/Finance/Instrument/Swap/Asset/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Swap/CreditDefault/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Swap/Currency/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Swap/Fpml/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Swap/Fpml/Util.daml
- src/main/daml/Daml/Finance/Instrument/Swap/InterestRate/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Swap/Util.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/Fpml.daml
- Implement logic described by the `paymentDaysOffset` FpML element
- Enable payment lag for the official FpML sample trade 3, which contains this feature.
Fixes https://github.com/digital-asset/daml-finance/issues/519
> Implement payment lag for FpML swaps

- src/main/daml/Daml/Finance/Instrument/Swap/Fpml/Util.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/Fpml.daml
- Support when the initialStep is not included in the steps list
- Support when not each calculationStep has a corresponding notional step.
- Enable the simpler way of specifying notional steps for the official FpML sample trade 2.
Fixes https://github.com/digital-asset/daml-finance/issues/520
> Improve parsing of notionalStepSchedule for FpML swaps

- src/main/daml/Daml/Finance/Instrument/Swap/Fpml/Instrument.daml
- src/main/daml/Daml/Finance/Instrument/Swap/Fpml/Util.daml
- src/main/daml/Daml/Finance/Interface/Instrument/Swap/Fpml/FpmlTypes.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/Fpml.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/Util.daml
- Implement official sample trade 5
- Add support for initial stub period that starts before the issue date of the swap
- Modify filtering and sanity checks of calculation periods to account for this
> Add FpML sample trade 5 and enhance stub period logic

- package/main/daml/Daml.Finance.Account/daml.yaml
- package/main/daml/Daml.Finance.Claims/daml.yaml
- package/main/daml/Daml.Finance.Data/daml.yaml
- package/main/daml/Daml.Finance.Holding/daml.yaml
- package/main/daml/Daml.Finance.Instrument.Bond/daml.yaml
- package/main/daml/Daml.Finance.Instrument.Equity/daml.yaml
- package/main/daml/Daml.Finance.Instrument.Generic/daml.yaml
- package/main/daml/Daml.Finance.Instrument.Swap/daml.yaml
- package/main/daml/Daml.Finance.Instrument.Token/daml.yaml
- package/main/daml/Daml.Finance.Lifecycle/daml.yaml
- package/main/daml/Daml.Finance.Settlement/daml.yaml
- package/main/daml/Daml.Finance.Util/daml.yaml
- package/test/daml/Daml.Finance.Util.Test/daml.yaml
The previous PR from @markus-da introduced a breaking changes to the package, hence the bump.
> Bump `Daml.Finance.Util` to 2.0.0

- src/main/daml/Daml/Finance/Holding/Fungible.daml
- src/test/daml/Daml/Finance/Holding/Test/Fungible.daml
this PR adds the following checks to the merge choice **implementation**:
1. list of fungibles to merge is non-empty
2. the account key of merged fungibles are the same
3. signatories of merged fungibles are the same 
and corresponding tests
> fix for fungible merge

- src/main/daml/Daml/Finance/Data/Time/DateClock.daml
- src/main/daml/Daml/Finance/Interface/Data/Reference/Time.daml
- src/test/daml/Daml/Finance/Data/Test/DateClock.daml
Reopening of #631.
This PR proposes making Advance and Rewind of the Time interface consuming. Alternatively, if choices are required to be nonconsuming at the interface level, then archival can be push to the implementation level in DateClock instead.
> `DateClock` key violation on `nonconsuming` `Advance` and `Rewind` interface choices.

- Makefile
- docs/scripts/build-assembly.sh
> update docs base url, make assembly backwards-compatible

- Makefile
- daml.yaml
- docs/scripts/build-assembly.sh
https://github.com/digital-asset/daml-finance/pull/669
This also bumps assembly to `1.1.5`
> Backport #669

- src/main/daml/ContingentClaims/Valuation/Stochastic.daml
Remove a sentence referring to a white paper which we do not have.
> remove reference to white paper

- src/test/daml/Daml/Finance/Instrument/Generic/Test/CallableBond.daml
Currently, the generic callable bond example only contains one coupon, so it does not show any nesting of claims. I have added a 2nd coupon to make the example a bit more realistic and to show claims nesting. 
I also added a separate principal amount in case of a call, to make it possible to add a call premium if desired.
> Add features to generic callable bond

- src/main/daml/ContingentClaims/Core/Claim.daml
- src/main/daml/ContingentClaims/Core/Observation.daml
- src/main/daml/ContingentClaims/Lifecycle/Util.daml
- src/main/daml/ContingentClaims/Valuation/Stochastic.daml
- src/main/daml/Daml/Finance/Claims/Util/Builders.daml
- src/test/daml/ContingentClaims/Test/Lifecycle.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/Asset.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/CreditDefault.daml
Fixes https://github.com/digital-asset/daml-finance/issues/767
I had an idea around contingent claims and it turns out it could be implemented rather quickly.
The problem:
- observations within a `scale` node are evaluated at `t` = the acquisition time of the sub-contract
- this makes it cumbersome to write expressions for an observable which is observed at different points in time
Ex.1 performance-linked payoff
The Observation in this case is of the form `S(t_1) / S(t_0) - 1`
Currently we need to write this as
`when (at t_0) $ scale (Const 1.0 / Observe S) $ when (at t_1) $ scale(Observe S) payoff and when (at t_1) $ give payoff` 
This expression is rather hard to read and the `payoff` sub-claim is duplicated. 
Ex 2. rate compounding
Rate compounding is currently implemented in a fashion …
> Add an `ObserveAt` observation builder which is observed at an explicit point in time

- CHANGELOG.md
- src/main/daml/Daml/Finance/Account/Account.daml
- src/main/daml/Daml/Finance/Data/Numeric/Observation.daml
- src/main/daml/Daml/Finance/Data/Reference/HolidayCalendar.daml
- src/main/daml/Daml/Finance/Holding/Fungible.daml
- src/main/daml/Daml/Finance/Holding/NonFungible.daml
- src/main/daml/Daml/Finance/Holding/NonTransferable.daml
- src/main/daml/Daml/Finance/Interface/Data/Numeric/Observation/Factory.daml
- src/main/daml/Daml/Finance/Interface/Data/Reference/HolidayCalendar/Factory.daml
- src/main/daml/Daml/Finance/Interface/Holding/Factory.daml
- src/main/daml/Daml/Finance/Interface/Holding/Fungible.daml
- src/main/daml/Daml/Finance/Interface/Lifecycle/Election/Factory.daml
- src/main/daml/Daml/Finance/Lifecycle/Election.daml
- src/test/daml/Daml/Finance/Data/Test/HolidayCalendar.daml
- src/test/daml/Daml/Finance/Data/Test/Observation.daml
Eliminates the "Remove" choices that serve as substitutes for `archive`. 
It retains the "Remove" choices for both the `Account` and `Instrument` factories, as these essentially function as "RemoveByKey" choices, and they also conveniently obfuscate the workaround we've implemented for keying interfaces. 
The redundant `ArchiveFungible` choice was also removed.
Fixes [889](https://github.com/digital-asset/daml-finance/issues/889)
> Eliminate unnecessary Remove choices and the ArchiveFungible choice

- src/main/daml/Daml/Finance/Lifecycle/Rule/ClaimWithCompression.daml
- src/main/daml/Daml/Finance/Lifecycle/Rule/ClaimWithNonTargetCompression.daml
- src/test/daml/Daml/Finance/Instrument/Generic/Test/Intermediated/BondCouponWithCompression.daml
- src/test/daml/Daml/Finance/Lifecycle/Test/Compression.daml
Merging into a side-branch for now. 
This PR adds a version of the `Claim` rule that "compresses" settlement `Steps` on the cash leg, bypassing intermediaries.
I originally applied compression directly on `RoutedSteps` (within the `RouteProvider`) but then realised that this forces the intermediaries to be in the route, which might be undesirable.
The `compress` function however works for both `Steps` and `RoutedSteps` (as they both form a set of directed graphs). If we think it is a valuable addition to the library, we can
- move it to a common place (to be defined, could be in `D.F.Settlement`)
- use a type-class to abstract graph-like structures
- have `Step` and `RoutedStep` implement such a type-class
> Add claim rule that compresses steps on the cash leg

- .circleci/config.yml
Avoid downloading `dar` dependencies from GitHub for every build by the CI.
Utilises the CircleCI caching to store the `.cache` directory (which contains all the downloaded GitHub dependencies). This directory is already used locally to avoid unnecessary downloads from GitHub.
> Add daml caching to CI

- src/main/daml/ContingentClaims/Core/Claim.daml
- src/main/daml/ContingentClaims/Core/Internal/Claim.daml
- src/main/daml/ContingentClaims/Core/Observation.daml
I explain what the constructor does rather than re-directing to the corresponding element in the `Claim` data type (which we are trying to hide from our users)
> Simplify description of claim constructors

- src/main/daml/Daml/Finance/Instrument/Token/Instrument.daml
- src/main/daml/Daml/Finance/Interface/Instrument/Base/Instrument.daml
- src/main/daml/Daml/Finance/Interface/Instrument/Token/Instrument.daml
- src/main/daml/Daml/Finance/Interface/Instrument/Token/Types.daml
We shouldn't characterise the `Token` instrument as not defining any lifecycling logic. This is because we can process e.g. `Distribution` events for a Token, and we do so in the getting started lifecycling tutorial
> improve token instrument description

- CHANGELOG.md
- src/main/daml/Daml/Finance/Util/Date/RollConvention.daml
- src/test/daml/Daml/Finance/Util/Test/Date/RollConvention.daml
This PR fixes the previously broken behaviour when using `DOM 31` as roll convention.
Fixes https://github.com/digital-asset/daml-finance/issues/1006
> Improve schedule rollout logic

- CHANGELOG.md
- package/test/daml/Daml.Finance.Test.Util/daml.yaml
- src/main/daml/Daml/Finance/Settlement/Batch.daml
- src/main/daml/Daml/Finance/Util/Common.daml
- src/test/daml/Daml/Finance/Settlement/Test/BatchWithIntermediaries.daml
- src/test/daml/Daml/Finance/Test/Util/FungibleV2.daml
https://github.com/digital-asset/daml-finance/issues/123
The check for consistent settled holdings has changed. Now, holdings of the same instrument don't  need identical `templateTypeRep`. Instead, they should share the same token standard: `Fungible`, `NonFungible`, or `NonTransferable` (implementation variations are allowed).
> Relaxed the settlement consistency check

- CHANGELOG.md
- src/main/daml/Daml/Finance/Interface/Account/Account.daml
@matteolimberto-da As we discussed at some point, I think it indeed makes sense to relax the `Account.I` to not require `Lockable.I`. We still provide a lockable account implementation, but a user of the library has the option to implement an "unlockable" account implementation if they prefer.
> Relax account to not require lockable

- src/test/daml/Daml/Finance/Account/Test/Account.daml
- src/test/daml/Daml/Finance/Holding/Test/Common.daml
- src/test/daml/Daml/Finance/Holding/Test/Transferable.daml
- src/test/daml/Daml/Finance/Holding/Test/Upgrade.daml
- src/test/daml/Daml/Finance/Instrument/Equity/Test/DivOption.daml
- src/test/daml/Daml/Finance/Instrument/Equity/Test/Dividend.daml
- src/test/daml/Daml/Finance/Instrument/Equity/Test/Merger.daml
- src/test/daml/Daml/Finance/Instrument/Equity/Test/RightsIssue.daml
- src/test/daml/Daml/Finance/Instrument/Equity/Test/StockSplit.daml
- src/test/daml/Daml/Finance/Instrument/Generic/Test/CallableBond.daml
- src/test/daml/Daml/Finance/Instrument/Generic/Test/EuropeanOption.daml
- src/test/daml/Daml/Finance/Instrument/Generic/Test/ForwardCash.daml
- src/test/daml/Daml/Finance/Instrument/Generic/Test/ForwardPhysical.daml
- src/test/daml/Daml/Finance/Instrument/Generic/Test/Intermediated/BondCoupon.daml
- src/test/daml/Daml/Finance/Instrument/Generic/Test/ReverseConvertible.daml
- src/test/daml/Daml/Finance/Instrument/Swap/Test/ForeignExchange.daml
- src/test/daml/Daml/Finance/Settlement/Test/Batch.daml
- src/test/daml/Daml/Finance/Settlement/Test/BatchWithIntermediaries.daml
- src/test/daml/Daml/Finance/Settlement/Test/Intermediated.daml
- src/test/daml/Daml/Finance/Settlement/Test/Transfer.daml
- src/test/daml/Daml/Finance/Test/Util/Holding.daml
- src/test/daml/Daml/Finance/Test/Util/HoldingFactory.daml
Fixes https://github.com/digital-asset/daml-finance/issues/115
> Adding upgrade scenario

- src/main/daml/Daml/Finance/Settlement/Batch.daml
- src/main/daml/Daml/Finance/Settlement/HTLC.daml
- src/main/daml/Daml/Finance/Settlement/Instruction.daml
- src/test/daml/Daml/Finance/Settlement/Test/TransferWithHTLC.daml
This PR relaxes the `Cancel` choice for the HTLC `Batch` with the following changes:
1. It allows the cancellation of a `Batch` that is either in the `Open` state or has expired.
2. It enables the `instructor` to cancel the `Batch` even if its `Instruction`s have been `Approved` and `Allocated`, removing the requirement to first unapprove or unallocate them.
Previously, the `Cancel` choice of the `Batch` required the HTLC to be expired, preventing cancellation while in the `Open` (and non-expired) state.
> `Batch` with HTLC / Relax the `Cancel` choice

- CHANGELOG.md
- daml.yaml
- shell.nix
This is to update docs.daml.com with the new version numbers for the experimental packages.
> Generate a new assembly and reset the changelog
